import { normalizeCoinsOnSurfaces } from './eraLevelLayout.js';
import { compileAuthoredEraLayout } from './eraAuthoredLayout.js';

function surface(id, offsetX, offsetZ, w, d, surfaceType, extra = {}) {
  return {
    id,
    offsetX,
    offsetZ,
    w,
    d,
    h: extra.h ?? 0.52,
    surfaceType,
    ...extra,
  };
}

function block(name, offsetX, offsetZ, w, h, d, extra = {}) {
  return {
    name,
    offsetX,
    offsetZ,
    w,
    h,
    d,
    ...extra,
  };
}

function column(name, offsetX, offsetZ, diameter, height, extra = {}) {
  return {
    name,
    offsetX,
    offsetZ,
    diameter,
    height,
    ...extra,
  };
}

function platform(name, offsetX, offsetZ, w, h, d, extra = {}) {
  return {
    name,
    offsetX,
    offsetZ,
    w,
    h,
    d,
    ...extra,
  };
}

const LEVEL5_CAMERA_PRESETS = {
  standard: {
    id: 'standard',
    label: 'Standard',
    distance: 7.2,
    height: 3.4,
    focusHeight: 1.14,
    lookAhead: 3.0,
    fov: 0.94,
  },
  closer: {
    id: 'closer',
    label: 'Closer Over-Shoulder',
    distance: 5.8,
    height: 2.8,
    focusHeight: 1.08,
    lookAhead: 2.4,
    fov: 0.98,
  },
};

const BASE_LEVEL5 = compileAuthoredEraLayout({
  totalCollectibles: 18,
  spawnYaw: 0.34,
  defaultCameraPreset: 'closer',
  cameraPresets: LEVEL5_CAMERA_PRESETS,
  spawn: { x: -61.4, y: 1.28, z: 0.2 },
  goal: { x: 60.8, y: 2.02, z: 24.2 },
  theme: 'aquarium',
  showGroundVisual: false,
  showRouteRibbons: false,

  acts: [
    { id: 'A', label: 'Arrival Threshold + Route Split', range: [-66, -34] },
    { id: 'B', label: 'Exhibit Spine + Hero Chamber', range: [-34, 10] },
    { id: 'C', label: 'Observation + Filtration + Trench', range: [10, 32] },
    { id: 'D', label: 'Pump Gallery + Nursery', range: [32, 68] },
  ],

  authoredMap: {
    id: 'aquarium-drift-map05-final',
    startSector: 'arrival_airlock_vestibule',
    goalSector: 'nursery_recovery_alcove',
    sectors: [
      {
        id: 'arrival_airlock_vestibule',
        label: 'Arrival Airlock Vestibule',
        x: -60,
        z: 0,
        w: 16,
        d: 12,
        floorY: 0.84,
        ceilingY: 5.8,
        floorSurfaceType: 'wet_service_deck',
        wallLanguage: 'arrival_airlock',
        landmarks: ['arrival display tank', 'fork bulkhead'],
        shell: {
          rgb: [24, 66, 82],
          roughness: 0.84,
          wallThickness: 1.2,
          floorSkirt: 0.56,
          openSides: ['east'],
          solid: true,
          ceiling: true,
          beamCount: 1,
        },
        surfaces: [
          surface('arrival_floor', -0.6, 0.0, 13.8, 9.2, 'wet_service_deck', {
            floorY: 0.84,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('arrival_display_apron', -4.0, 3.2, 4.8, 3.4, 'exhibit_deck', {
            floorY: 0.88,
            walkableClassification: 'guest-bay',
            roomSurface: true,
          }),
          surface('arrival_service_notch', 3.8, -2.6, 4.2, 3.2, 'shell_service_deck', {
            floorY: 0.80,
            walkableClassification: 'service-bay',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('arrival_display_wall', -4.2, 3.8, 6.2, 5.2, 0.8, {
            rgb: [56, 152, 176],
            emissiveScale: 0.10,
            roughness: 0.36,
            alpha: 0.78,
          }),
          block('arrival_display_volume', -4.2, 6.8, 5.6, 4.8, 4.6, {
            rgb: [24, 92, 118],
            emissiveScale: 0.04,
            roughness: 0.34,
            alpha: 0.24,
            solid: true,
          }),
          block('arrival_fork_bulkhead', 3.8, 0.0, 3.8, 5.4, 8.2, {
            rgb: [24, 68, 82],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('arrival_public_jamb', 5.8, 3.2, 1.8, 4.8, 2.8, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('arrival_service_jamb', 5.8, -3.2, 1.8, 4.8, 2.8, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('arrival_orientation_kiosk', -7.0, -1.8, 2.8, 2.2, 1.6, {
            rgb: [70, 108, 118],
            roughness: 0.78,
            emissiveScale: 0.03,
          }),
          block('arrival_lower_hull', -0.2, 0.0, 12.0, 2.8, 8.4, {
            y: -0.64,
            rgb: [14, 34, 42],
            roughness: 0.94,
            emissiveScale: 0.02,
            solid: true,
          }),
        ],
        decorColumns: [
          column('arrival_display_post_l', -6.8, 3.8, 0.72, 5.8, {
            rgb: [88, 178, 196],
            roughness: 0.48,
          }),
          column('arrival_display_post_r', -1.6, 3.8, 0.72, 5.8, {
            rgb: [88, 178, 196],
            roughness: 0.48,
          }),
        ],
        signage: [
          { offsetX: -2.0, y: 4.9, offsetZ: -4.8, text: 'ARRIVAL AIRLOCK', width: 7.2, height: 1.6 },
        ],
      },
      {
        id: 'public_exhibit_spine',
        label: 'Public Exhibit Spine',
        x: -44,
        z: 13,
        w: 18,
        d: 14,
        floorY: 0.96,
        ceilingY: 6.4,
        floorSurfaceType: 'viewing_deck',
        wallLanguage: 'public_gallery',
        landmarks: ['north exhibit wall', 'touch-pool alcove'],
        shell: {
          rgb: [24, 72, 88],
          roughness: 0.80,
          wallThickness: 1.2,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('public_main_walk', -0.8, -0.4, 13.2, 8.8, 'viewing_deck', {
            floorY: 0.96,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('public_north_view_bay', -1.0, 4.8, 10.0, 2.8, 'exhibit_deck', {
            floorY: 1.00,
            walkableClassification: 'guest-bay',
            roomSurface: true,
          }),
          surface('public_touch_pool_apron', 5.4, -3.2, 3.4, 2.6, 'exhibit_deck', {
            floorY: 1.00,
            walkableClassification: 'teaching-apron',
            roomSurface: true,
          }),
        ],
        checkpoints: [
          { id: 'cp_public_spine', offsetX: 0.8, offsetZ: 0.8, label: 'Public Exhibits' },
        ],
        decorBlocks: [
          block('public_north_tank_wall', 0.0, 7.0, 14.4, 6.0, 0.8, {
            rgb: [54, 148, 172],
            emissiveScale: 0.10,
            roughness: 0.38,
            alpha: 0.74,
          }),
          block('public_north_tank_volume', 0.0, 10.4, 13.4, 5.4, 5.8, {
            rgb: [24, 90, 116],
            emissiveScale: 0.04,
            roughness: 0.34,
            alpha: 0.24,
            solid: true,
          }),
          block('public_touch_pool_frame', 5.8, -1.4, 3.8, 3.6, 0.8, {
            rgb: [56, 150, 174],
            emissiveScale: 0.08,
            roughness: 0.42,
            alpha: 0.66,
          }),
          block('public_touch_pool_volume', 6.0, -4.2, 4.2, 3.4, 4.6, {
            rgb: [24, 96, 120],
            emissiveScale: 0.04,
            roughness: 0.34,
            alpha: 0.26,
            solid: true,
          }),
          block('public_touch_pool_backwall', 5.8, -6.8, 4.8, 3.8, 1.2, {
            rgb: [18, 44, 56],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('public_touch_pool_side_partition', 3.2, -3.6, 1.4, 4.0, 4.8, {
            rgb: [20, 54, 66],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('public_south_display_wall', -0.8, -5.8, 13.4, 3.8, 1.0, {
            rgb: [36, 86, 102],
            roughness: 0.72,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('public_center_partition', 1.8, 0.8, 2.6, 4.8, 5.2, {
            rgb: [24, 68, 82],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('public_south_wall_mass', -1.2, -6.4, 13.8, 4.8, 1.8, {
            rgb: [22, 62, 76],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('public_touch_pool_sidewall', 7.0, -3.0, 1.6, 4.2, 4.8, {
            rgb: [22, 64, 78],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('public_east_bulkhead_n', 7.0, 4.4, 2.6, 5.2, 4.0, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('public_east_bulkhead_s', 7.0, -4.2, 2.6, 5.2, 4.8, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('public_center_kiosk', -4.8, -1.4, 3.2, 2.2, 2.2, {
            rgb: [72, 110, 120],
            roughness: 0.78,
            emissiveScale: 0.03,
          }),
          block('public_lower_hull', -0.6, 0.0, 13.2, 2.6, 9.2, {
            y: -0.54,
            rgb: [14, 34, 42],
            roughness: 0.94,
            emissiveScale: 0.02,
            solid: true,
          }),
          block('public_ceiling_drop', -1.2, 0.8, 11.2, 0.54, 7.2, {
            y: 5.26,
            rgb: [22, 60, 74],
            roughness: 0.84,
            emissiveScale: 0.03,
          }),
          block('public_viewing_header', -0.8, 5.8, 12.0, 0.38, 1.4, {
            y: 4.8,
            rgb: [92, 180, 196],
            roughness: 0.36,
            emissiveScale: 0.10,
          }),
        ],
        decorColumns: [
          column('public_north_post_l', -6.6, 7.0, 0.70, 6.0, {
            rgb: [86, 180, 196],
            roughness: 0.48,
          }),
          column('public_north_post_r', 6.6, 7.0, 0.70, 6.0, {
            rgb: [86, 180, 196],
            roughness: 0.48,
          }),
        ],
        signage: [
          { offsetX: 2.8, y: 5.0, offsetZ: -6.0, text: 'PUBLIC EXHIBITS', width: 6.4, height: 1.5 },
        ],
      },
      {
        id: 'service_access_elbow',
        label: 'Service Access Elbow',
        x: -44,
        z: -12,
        w: 16,
        d: 12,
        floorY: 0.82,
        ceilingY: 5.6,
        floorSurfaceType: 'catwalk_grate',
        wallLanguage: 'service_corridor',
        landmarks: ['staff bay', 'warning rail'],
        shell: {
          rgb: [20, 58, 72],
          roughness: 0.86,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('service_main_walk', -0.6, 0.0, 12.4, 5.0, 'catwalk_grate', {
            floorY: 0.82,
            walkableClassification: 'service-floor',
            roomSurface: true,
          }),
          surface('service_side_bay', 4.8, 2.2, 5.8, 4.2, 'maintenance_plate', {
            floorY: 0.78,
            walkableClassification: 'service-bay',
            roomSurface: true,
          }),
          surface('service_dry_strip', -1.4, -2.6, 10.0, 2.8, 'shell_service_deck', {
            floorY: 0.76,
            walkableClassification: 'dry-edge',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('service_pipe_rack', -0.6, 3.6, 11.8, 0.8, 0.8, {
            y: 3.76,
            rgb: [96, 170, 182],
            roughness: 0.40,
            emissiveScale: 0.06,
          }),
          block('service_locker_bank', 5.4, -3.8, 3.2, 3.8, 1.6, {
            rgb: [56, 92, 104],
            roughness: 0.80,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('service_south_equipment', -2.2, -4.8, 7.2, 2.2, 1.4, {
            rgb: [44, 78, 90],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('service_east_jamb_n', 6.8, 3.0, 1.8, 4.8, 3.8, {
            rgb: [20, 56, 68],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('service_east_jamb_s', 6.8, -3.0, 1.8, 4.8, 3.8, {
            rgb: [20, 56, 68],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('service_lower_hull', 0.0, 0.0, 12.0, 2.6, 6.2, {
            y: -0.62,
            rgb: [12, 30, 38],
            roughness: 0.94,
            emissiveScale: 0.02,
            solid: true,
          }),
          block('service_ceiling_duct', -1.2, 0.0, 10.8, 0.50, 2.4, {
            y: 4.86,
            rgb: [22, 58, 70],
            roughness: 0.82,
            emissiveScale: 0.03,
          }),
        ],
        signage: [
          { offsetX: 3.4, y: 4.4, offsetZ: -4.8, text: 'STAFF ACCESS', width: 5.2, height: 1.4 },
        ],
      },
      {
        id: 'wet_pipe_gallery',
        label: 'Wet Pipe Gallery',
        x: -28,
        z: -10,
        w: 14,
        d: 10,
        floorY: 0.82,
        ceilingY: 5.6,
        floorSurfaceType: 'catwalk_grate',
        wallLanguage: 'wet_pipe_gallery',
        landmarks: ['manifold wall', 'oxygen station'],
        shell: {
          rgb: [20, 56, 68],
          roughness: 0.88,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('wet_pipe_walk', -0.4, 0.0, 12.0, 4.8, 'catwalk_grate', {
            floorY: 0.82,
            walkableClassification: 'service-floor',
            roomSurface: true,
          }),
          surface('wet_pipe_manifold_apron', 3.8, 2.0, 5.4, 4.0, 'maintenance_plate', {
            floorY: 0.86,
            walkableClassification: 'service-bay',
            roomSurface: true,
          }),
          surface('wet_pipe_oxygen_bay', -3.4, -2.2, 4.2, 2.8, 'shell_service_deck', {
            floorY: 0.80,
            walkableClassification: 'utility-bay',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('wet_pipe_manifold_wall', 4.0, 3.6, 7.2, 4.4, 1.0, {
            rgb: [50, 98, 112],
            roughness: 0.72,
            emissiveScale: 0.04,
            solid: true,
          }),
          block('wet_pipe_oxygen_station', -3.8, -3.6, 1.8, 2.8, 1.2, {
            rgb: [68, 116, 126],
            roughness: 0.74,
            emissiveScale: 0.05,
            solid: true,
          }),
          block('wet_pipe_north_rack', -1.0, 4.0, 11.0, 0.8, 0.8, {
            y: 3.64,
            rgb: [96, 172, 184],
            roughness: 0.40,
            emissiveScale: 0.06,
          }),
          block('wet_pipe_side_shoulder_l', -4.8, 0.0, 1.8, 4.4, 4.6, {
            rgb: [18, 52, 64],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('wet_pipe_side_shoulder_r', 5.8, 0.0, 1.8, 4.4, 4.6, {
            rgb: [18, 52, 64],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('wet_pipe_lower_hull', 0.0, 0.0, 10.8, 2.6, 5.2, {
            y: -0.70,
            rgb: [12, 28, 36],
            roughness: 0.94,
            emissiveScale: 0.02,
            solid: true,
          }),
          block('wet_pipe_ceiling_plenum', 0.0, 0.0, 10.8, 0.46, 3.0, {
            y: 4.84,
            rgb: [20, 54, 66],
            roughness: 0.84,
            emissiveScale: 0.03,
          }),
        ],
        signage: [
          { offsetX: 2.4, y: 4.4, offsetZ: -4.0, text: 'FILTRATION ACCESS', width: 6.0, height: 1.4 },
        ],
      },
      {
        id: 'chamber_reveal_gallery',
        label: 'Chamber Reveal Gallery',
        x: -28,
        z: 19,
        w: 14,
        d: 12,
        floorY: 1.02,
        ceilingY: 6.4,
        floorSurfaceType: 'viewing_deck',
        wallLanguage: 'reveal_gallery',
        landmarks: ['corner reveal wall', 'preview tank slice'],
        shell: {
          rgb: [22, 66, 80],
          roughness: 0.84,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: true,
          beamCount: 2,
        },
        surfaces: [
          surface('reveal_entry_run', -2.0, -0.8, 10.8, 5.0, 'viewing_deck', {
            floorY: 1.02,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('reveal_turn_pad', 2.2, 3.0, 6.2, 7.2, 'exhibit_deck', {
            floorY: 1.08,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('reveal_corner_wall', 0.4, 0.0, 4.8, 5.2, 6.0, {
            rgb: [24, 68, 82],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('reveal_preview_tank_wall', -2.6, 4.6, 5.8, 4.8, 0.8, {
            rgb: [56, 150, 172],
            roughness: 0.38,
            emissiveScale: 0.08,
            alpha: 0.72,
          }),
          block('reveal_preview_tank_volume', -2.6, 7.4, 5.4, 4.2, 3.6, {
            rgb: [24, 92, 116],
            roughness: 0.34,
            emissiveScale: 0.04,
            alpha: 0.20,
            solid: true,
          }),
          block('reveal_south_portal_jamb', 4.8, -4.0, 2.0, 5.0, 3.2, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('reveal_lower_hull', 0.0, 1.0, 9.0, 2.6, 7.0, {
            y: -0.56,
            rgb: [14, 34, 42],
            roughness: 0.94,
            emissiveScale: 0.02,
            solid: true,
          }),
          block('reveal_east_header', 5.8, 2.0, 1.6, 0.40, 5.6, {
            y: 4.92,
            rgb: [22, 66, 80],
            roughness: 0.82,
            emissiveScale: 0.03,
          }),
        ],
      },
      {
        id: 'main_tank_chamber',
        label: 'Main Tank Chamber',
        x: -1,
        z: 10,
        w: 24,
        d: 20,
        floorY: 1.06,
        ceilingY: 9.4,
        floorSurfaceType: 'exhibit_deck',
        wallLanguage: 'hero_tank_chamber',
        landmarks: ['dominant tank wall', 'filtration ring', 'upper bridge', 'lower route'],
        shell: {
          rgb: [20, 60, 74],
          roughness: 0.84,
          wallThickness: 1.3,
          floorSkirt: 0.56,
          openSides: ['west', 'south'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('chamber_entry_gallery', -6.8, 1.2, 9.8, 9.8, 'viewing_deck', {
            floorY: 1.06,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('chamber_north_concourse', -1.0, 6.8, 14.6, 4.2, 'viewing_deck', {
            floorY: 1.10,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('chamber_east_machine_apron', 7.2, 1.0, 6.0, 9.2, 'exhibit_deck', {
            floorY: 1.14,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('chamber_south_service_lip', 0.8, -5.4, 12.0, 3.2, 'shell_service_deck', {
            floorY: 0.98,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        checkpoints: [
          { id: 'cp_hero_chamber', offsetX: -7.0, offsetZ: 2.6, label: 'Main Tank Chamber' },
        ],
        decorBlocks: [
          block('chamber_entry_shoulder', -10.4, 3.8, 3.8, 6.0, 8.4, {
            rgb: [24, 68, 82],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_entry_mask', -6.2, 7.0, 3.8, 5.8, 4.4, {
            rgb: [24, 70, 84],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_tank_front_wall', -1.2, 7.2, 12.8, 7.0, 1.0, {
            rgb: [58, 154, 176],
            roughness: 0.38,
            emissiveScale: 0.10,
            alpha: 0.80,
          }),
          block('chamber_tank_volume', -1.2, 11.6, 11.8, 6.6, 9.4, {
            rgb: [22, 90, 116],
            roughness: 0.34,
            emissiveScale: 0.04,
            alpha: 0.26,
            solid: true,
          }),
          block('chamber_tank_side_w', -7.2, 11.6, 1.0, 6.6, 9.4, {
            rgb: [68, 160, 184],
            roughness: 0.38,
            emissiveScale: 0.10,
            alpha: 0.72,
          }),
          block('chamber_tank_side_e', 4.8, 11.6, 1.0, 6.6, 9.4, {
            rgb: [68, 160, 184],
            roughness: 0.38,
            emissiveScale: 0.10,
            alpha: 0.72,
          }),
          block('chamber_tank_base', -1.2, 11.6, 12.2, 1.8, 10.0, {
            y: 0.28,
            rgb: [24, 56, 68],
            roughness: 0.78,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_north_backing_wall', -1.0, 17.8, 15.4, 7.6, 1.2, {
            rgb: [22, 64, 80],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_landmark_machine', 10.0, 2.0, 4.8, 6.8, 6.2, {
            rgb: [36, 96, 112],
            roughness: 0.62,
            emissiveScale: 0.05,
            solid: true,
          }),
          block('chamber_landmark_base', 10.0, 2.0, 7.2, 2.0, 8.0, {
            y: 0.72,
            rgb: [42, 84, 96],
            roughness: 0.72,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_landmark_stack', 11.2, 5.6, 2.2, 7.8, 2.2, {
            rgb: [72, 154, 176],
            roughness: 0.40,
            emissiveScale: 0.08,
            alpha: 0.34,
            solid: true,
          }),
          block('chamber_observation_portal', 10.6, 9.8, 2.6, 5.8, 5.4, {
            rgb: [20, 60, 74],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_filtration_lip', 5.6, -6.8, 5.4, 1.0, 4.8, {
            y: 0.92,
            rgb: [62, 104, 116],
            roughness: 0.70,
            emissiveScale: 0.03,
          }),
          block('chamber_lower_route_frame', 5.8, -4.2, 4.4, 5.0, 5.8, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_lower_route_jamb_w', 1.8, -8.2, 3.8, 5.2, 2.2, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_lower_route_jamb_e', 9.2, -8.2, 3.8, 5.2, 2.2, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_east_shoulder', 11.8, 2.4, 2.2, 6.8, 12.2, {
            rgb: [20, 58, 72],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_south_machine_bank', -1.2, -8.8, 14.0, 4.6, 2.6, {
            rgb: [28, 66, 78],
            roughness: 0.80,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_entry_canopy', -7.6, 3.8, 8.0, 0.60, 7.0, {
            y: 5.36,
            rgb: [24, 62, 76],
            roughness: 0.84,
            emissiveScale: 0.03,
          }),
          block('chamber_west_jamb_n', -12.0, 6.8, 2.2, 6.0, 4.6, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('chamber_west_jamb_s', -12.0, -2.6, 2.2, 6.0, 5.2, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
        ],
        decorColumns: [
          column('chamber_filtration_ring_a', 12.0, 10.8, 2.6, 7.2, {
            rgb: [76, 168, 188],
            roughness: 0.44,
            emissiveScale: 0.06,
            alpha: 0.34,
            solid: true,
          }),
          column('chamber_filtration_ring_b', 15.2, 14.0, 2.2, 7.8, {
            rgb: [76, 170, 190],
            roughness: 0.44,
            emissiveScale: 0.06,
            alpha: 0.34,
            solid: true,
          }),
          column('chamber_filtration_ring_c', 10.2, 15.6, 2.0, 6.8, {
            rgb: [76, 170, 190],
            roughness: 0.44,
            emissiveScale: 0.06,
            alpha: 0.34,
            solid: true,
          }),
          column('chamber_tank_cluster_main', 7.4, 9.6, 3.8, 6.2, {
            rgb: [84, 186, 204],
            roughness: 0.34,
            emissiveScale: 0.08,
            alpha: 0.26,
            solid: true,
          }),
          column('chamber_tank_cluster_small', 10.4, 11.8, 2.4, 5.6, {
            rgb: [84, 186, 204],
            roughness: 0.34,
            emissiveScale: 0.08,
            alpha: 0.24,
            solid: true,
          }),
        ],
        decorPlatforms: [
          platform('chamber_top_frame_north', -1.2, 18.8, 15.6, 0.26, 1.0, {
            y: 7.2,
            rgb: [28, 82, 96],
          }),
          platform('chamber_top_frame_east', 10.8, 10.2, 1.0, 0.26, 12.0, {
            y: 7.2,
            rgb: [28, 82, 96],
          }),
        ],
        signage: [
          { offsetX: -1.6, y: 6.2, offsetZ: -11.4, text: 'MAIN TANK CHAMBER', width: 8.0, height: 1.7 },
        ],
      },
      {
        id: 'upper_observation_bridge',
        label: 'Upper Observation Bridge',
        x: 16,
        z: 18,
        w: 12,
        d: 6,
        floorY: 3.14,
        ceilingY: 6.4,
        floorSurfaceType: 'catwalk_grate',
        wallLanguage: 'observation_bridge',
        landmarks: ['bridge overlook', 'tank overlook'],
        shell: {
          rgb: [20, 56, 70],
          roughness: 0.80,
          wallThickness: 0.9,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('upper_bridge_main', 0.0, 0.0, 9.4, 3.6, 'catwalk_grate', {
            floorY: 3.14,
            walkableClassification: 'bridge',
          }),
          surface('upper_bridge_overlook', -2.4, 1.6, 4.2, 2.0, 'viewing_deck', {
            floorY: 3.18,
            walkableClassification: 'lookout',
          }),
        ],
        decorBlocks: [
          block('upper_bridge_underhull', 0.0, 0.0, 9.4, 2.2, 4.2, {
            y: 1.86,
            rgb: [16, 36, 46],
            roughness: 0.94,
            emissiveScale: 0.02,
            solid: true,
          }),
          block('upper_bridge_pipe_truss', 0.0, -1.8, 9.8, 0.8, 0.8, {
            y: 4.82,
            rgb: [92, 166, 182],
            roughness: 0.40,
            emissiveScale: 0.06,
          }),
          block('upper_bridge_window_band', 0.0, 2.0, 9.8, 1.8, 0.5, {
            y: 4.0,
            rgb: [58, 152, 174],
            roughness: 0.34,
            emissiveScale: 0.08,
            alpha: 0.30,
          }),
        ],
        decorColumns: [
          column('upper_bridge_support_l', -3.8, 0.0, 0.72, 3.2, {
            y: 1.56,
            rgb: [56, 102, 116],
            roughness: 0.62,
            solid: true,
          }),
          column('upper_bridge_support_r', 3.8, 0.0, 0.72, 3.2, {
            y: 1.56,
            rgb: [56, 102, 116],
            roughness: 0.62,
            solid: true,
          }),
        ],
      },
      {
        id: 'filtration_core',
        label: 'Filtration Core',
        x: 18,
        z: -2,
        w: 18,
        d: 14,
        floorY: 0.82,
        ceilingY: 6.2,
        floorSurfaceType: 'wet_service_deck',
        wallLanguage: 'filtration_room',
        landmarks: ['spill gate', 'manifold wall'],
        shell: {
          rgb: [20, 56, 70],
          roughness: 0.84,
          wallThickness: 1.2,
          floorSkirt: 0.56,
          openSides: ['west', 'south'],
          solid: true,
          ceiling: true,
          beamCount: 2,
        },
        surfaces: [
          surface('core_safe_walk', -4.8, -0.2, 4.6, 10.4, 'wet_service_deck', {
            floorY: 0.82,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('core_spill_lane', 1.8, -0.8, 8.0, 8.8, 'maintenance_plate', {
            floorY: 0.88,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('core_north_apron', -0.8, 4.8, 10.8, 3.2, 'shell_service_deck', {
            floorY: 0.86,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        checkpoints: [
          { id: 'cp_filtration_core', offsetX: -1.8, offsetZ: 0.0, label: 'Filtration Core' },
        ],
        decorBlocks: [
          block('core_basin_volume', 3.6, 0.2, 6.8, 4.4, 6.8, {
            rgb: [28, 94, 112],
            roughness: 0.44,
            emissiveScale: 0.04,
            alpha: 0.18,
            solid: true,
          }),
          block('core_manifold_bank', 6.2, -4.8, 4.6, 4.6, 2.0, {
            rgb: [44, 94, 108],
            roughness: 0.70,
            emissiveScale: 0.04,
            solid: true,
          }),
          block('core_spill_gate_frame', 2.2, -1.0, 8.6, 4.6, 1.4, {
            rgb: [28, 74, 88],
            roughness: 0.70,
            emissiveScale: 0.04,
            solid: true,
          }),
          block('core_safe_curb', -1.4, -0.8, 1.0, 0.8, 9.0, {
            y: 0.74,
            rgb: [74, 118, 126],
            roughness: 0.72,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('core_safe_wall', -7.4, 0.0, 2.0, 4.8, 10.2, {
            rgb: [22, 60, 72],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('core_containment_post_l', 0.2, 0.4, 0.5, 3.4, 0.5, {
            y: 2.2,
            rgb: [78, 168, 188],
            roughness: 0.42,
            emissiveScale: 0.08,
            solid: true,
          }),
          block('core_containment_post_r', 7.0, 0.4, 0.5, 3.4, 0.5, {
            y: 2.2,
            rgb: [78, 168, 188],
            roughness: 0.42,
            emissiveScale: 0.08,
            solid: true,
          }),
          block('core_lower_hull', 0.0, -0.2, 12.8, 3.0, 10.0, {
            y: -0.64,
            rgb: [14, 34, 42],
            roughness: 0.92,
            emissiveScale: 0.02,
            solid: true,
          }),
        ],
        signage: [
          { offsetX: 3.8, y: 5.0, offsetZ: -5.8, text: 'LIVE SPILL GATE', width: 6.0, height: 1.5 },
        ],
      },
      {
        id: 'flooded_maintenance_trench',
        label: 'Flooded Maintenance Trench',
        x: 18,
        z: -18,
        w: 18,
        d: 10,
        floorY: 0.22,
        ceilingY: 4.4,
        floorSurfaceType: 'maintenance_channel',
        wallLanguage: 'flooded_trench',
        landmarks: ['drain bank', 'sump shelf'],
        shell: {
          rgb: [18, 44, 52],
          roughness: 0.88,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['north', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('trench_lower_lane', -3.8, 0.0, 11.0, 4.8, 'maintenance_channel', {
            floorY: 0.22,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('trench_safe_shelf', 4.4, 1.8, 6.2, 3.0, 'maintenance_plate', {
            floorY: 0.58,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('trench_exit_lip', 4.2, -2.4, 5.8, 2.4, 'maintenance_plate', {
            floorY: 0.46,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('trench_drain_bank', -8.0, 0.0, 3.0, 1.8, 7.2, {
            y: 0.08,
            rgb: [18, 30, 34],
            roughness: 0.92,
            emissiveScale: 0.02,
            solid: true,
          }),
          block('trench_sump_box', 6.8, 0.8, 3.8, 2.2, 2.6, {
            rgb: [34, 58, 64],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('trench_side_wall', 7.8, 0.0, 1.8, 3.2, 8.2, {
            rgb: [20, 46, 54],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('trench_backwall_glass', 0.0, 4.2, 14.8, 3.8, 0.6, {
            rgb: [46, 124, 146],
            roughness: 0.40,
            emissiveScale: 0.05,
            alpha: 0.18,
          }),
        ],
      },
      {
        id: 'pump_gallery_rejoin',
        label: 'Pump Gallery Rejoin',
        x: 38,
        z: -6,
        w: 16,
        d: 12,
        floorY: 1.00,
        ceilingY: 6.0,
        floorSurfaceType: 'shell_service_deck',
        wallLanguage: 'pump_gallery',
        landmarks: ['pump bank', 'rejoin elbow'],
        shell: {
          rgb: [22, 60, 74],
          roughness: 0.84,
          wallThickness: 1.1,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('pump_gallery_floor', -0.8, 0.0, 12.6, 8.8, 'shell_service_deck', {
            floorY: 1.00,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('pump_gallery_side', 4.2, 2.8, 5.6, 3.4, 'maintenance_plate', {
            floorY: 1.04,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('pump_gallery_ramp', -3.0, -3.0, 7.2, 3.8, 'wet_service_deck', {
            floorY: 0.92,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        checkpoints: [
          { id: 'cp_pump_gallery', offsetX: 0.0, offsetZ: 0.0, label: 'Pump Gallery' },
        ],
        decorBlocks: [
          block('pump_machine_bank', 5.0, -3.8, 5.8, 4.4, 2.2, {
            rgb: [44, 94, 108],
            roughness: 0.72,
            emissiveScale: 0.04,
            solid: true,
          }),
          block('pump_rejoin_bulkhead', -5.0, 2.0, 3.0, 4.8, 4.8, {
            rgb: [22, 64, 76],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('pump_north_baffle', 0.8, 4.8, 5.2, 4.6, 2.8, {
            rgb: [24, 68, 80],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('pump_lower_hull', 0.0, 0.0, 12.8, 3.0, 9.2, {
            y: -0.60,
            rgb: [14, 34, 42],
            roughness: 0.92,
            emissiveScale: 0.02,
            solid: true,
          }),
          block('pump_ceiling_bay', -0.6, 0.0, 10.8, 0.42, 4.2, {
            y: 4.92,
            rgb: [22, 60, 74],
            roughness: 0.82,
            emissiveScale: 0.03,
          }),
        ],
      },
      {
        id: 'nursery_compression_hall',
        label: 'Nursery Compression Hall',
        x: 48,
        z: 10,
        w: 10,
        d: 10,
        floorY: 1.18,
        ceilingY: 5.4,
        floorSurfaceType: 'shell_service_deck',
        wallLanguage: 'compression_hall',
        landmarks: ['goal baffle', 'nursery glow'],
        shell: {
          rgb: [22, 66, 80],
          roughness: 0.84,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'north'],
          solid: true,
          ceiling: true,
          beamCount: 0,
        },
        surfaces: [
          surface('compression_south', -1.6, -2.0, 7.0, 4.8, 'shell_service_deck', {
            floorY: 1.18,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('compression_turn', 1.6, 1.8, 4.8, 3.8, 'viewing_deck', {
            floorY: 1.42,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('compression_goal_baffle', 1.6, -0.2, 3.0, 4.8, 5.0, {
            rgb: [24, 70, 84],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('compression_turn_wall', -0.8, 3.8, 5.4, 4.2, 1.6, {
            rgb: [24, 70, 84],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('compression_entry_frame', -3.8, -0.2, 1.8, 4.6, 6.2, {
            rgb: [24, 68, 82],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('compression_nursery_glow_slice', 2.0, 4.0, 4.2, 3.2, 0.6, {
            rgb: [76, 164, 182],
            roughness: 0.34,
            emissiveScale: 0.10,
            alpha: 0.24,
          }),
          block('compression_lower_hull', 0.0, 0.0, 7.6, 2.6, 7.6, {
            y: -0.56,
            rgb: [14, 34, 42],
            roughness: 0.92,
            emissiveScale: 0.02,
            solid: true,
          }),
        ],
      },
      {
        id: 'nursery_recovery_alcove',
        label: 'Nursery Recovery Alcove',
        x: 58,
        z: 24,
        w: 16,
        d: 14,
        floorY: 1.76,
        ceilingY: 6.8,
        floorSurfaceType: 'exhibit_deck',
        wallLanguage: 'nursery_recovery_room',
        landmarks: ['recovery tank', 'goal alcove'],
        shell: {
          rgb: [24, 74, 90],
          roughness: 0.78,
          wallThickness: 1.2,
          floorSkirt: 0.56,
          openSides: ['west'],
          solid: true,
          ceiling: true,
          beamCount: 0,
        },
        surfaces: [
          surface('nursery_entry_apron', -4.8, -4.0, 6.4, 4.0, 'shell_service_deck', {
            floorY: 1.62,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('nursery_gallery', -0.8, 2.8, 10.2, 7.0, 'viewing_deck', {
            floorY: 1.78,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('goalDeck', 4.8, 1.2, 3.4, 3.6, 'exhibit_deck', {
            name: 'goalDeck',
            floorY: 1.92,
            walkableClassification: 'goal',
          }),
        ],
        decorBlocks: [
          block('nursery_recovery_wall', -0.6, 8.8, 11.8, 6.2, 0.8, {
            rgb: [54, 148, 172],
            roughness: 0.38,
            emissiveScale: 0.10,
            alpha: 0.72,
          }),
          block('nursery_recovery_volume', -0.6, 12.8, 11.0, 5.8, 6.2, {
            rgb: [24, 96, 120],
            roughness: 0.34,
            emissiveScale: 0.04,
            alpha: 0.24,
            solid: true,
          }),
          block('nursery_goal_backdrop', 5.0, 4.2, 7.0, 6.0, 2.6, {
            rgb: [26, 76, 90],
            roughness: 0.80,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('nursery_goal_backwall', 5.0, 7.0, 8.2, 6.2, 1.2, {
            rgb: [20, 66, 80],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('nursery_goal_canopy', 5.0, 0.8, 6.0, 0.24, 5.6, {
            y: 4.76,
            rgb: [110, 198, 212],
            roughness: 0.28,
            emissiveScale: 0.10,
          }),
          block('nursery_side_partition_l', -3.8, -0.8, 2.6, 4.8, 6.0, {
            rgb: [24, 68, 82],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('nursery_side_partition_r', 1.8, -0.8, 2.2, 4.8, 4.6, {
            rgb: [24, 68, 82],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('nursery_goal_frame_l', 2.8, 0.8, 1.2, 4.8, 4.8, {
            rgb: [24, 70, 84],
            roughness: 0.80,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('nursery_goal_frame_r', 7.0, 0.8, 1.2, 4.8, 4.8, {
            rgb: [24, 70, 84],
            roughness: 0.80,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('nursery_goal_niche_header', 5.0, 2.8, 6.4, 0.42, 4.8, {
            y: 4.54,
            rgb: [96, 184, 198],
            roughness: 0.32,
            emissiveScale: 0.10,
          }),
          block('nursery_goal_sidewall_l', 2.0, 2.2, 1.4, 4.8, 6.8, {
            rgb: [24, 68, 82],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('nursery_goal_sidewall_r', 8.0, 2.2, 1.4, 4.8, 6.8, {
            rgb: [24, 68, 82],
            roughness: 0.82,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('nursery_cradle_ring', 0.2, 3.6, 7.2, 0.30, 7.2, {
            y: 4.8,
            rgb: [110, 196, 210],
            roughness: 0.30,
            emissiveScale: 0.10,
          }),
        ],
        signage: [
          { offsetX: 0.4, y: 5.4, offsetZ: -5.4, text: 'RECOVERY NURSERY', width: 7.4, height: 1.6 },
        ],
      },
    ],
    connectors: [
      {
        id: 'arrival_to_public',
        label: 'Arrival Public Hall',
        sourceSector: 'arrival_airlock_vestibule',
        destinationSector: 'public_exhibit_spine',
        type: 'hall',
        x: -52,
        z: 7,
        w: 6,
        d: 10,
        floorY: 0.88,
        ceilingY: 5.8,
        floorSurfaceType: 'viewing_deck',
        shell: {
          rgb: [22, 62, 76],
          roughness: 0.84,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['north', 'south'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('arrival_public_floor', 0.0, 0.0, 6.0, 9.4, 'viewing_deck', {
            floorY: 0.88,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('arrival_public_turn_frame', 1.4, 1.8, 2.0, 4.8, 3.8, {
            rgb: [24, 68, 82],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('arrival_public_lower_hull', 0.0, 0.0, 5.4, 2.6, 8.6, {
            y: -0.70,
            rgb: [14, 34, 42],
            roughness: 0.94,
            emissiveScale: 0.02,
            solid: true,
          }),
        ],
      },
      {
        id: 'arrival_to_service',
        label: 'Arrival Service Hatch',
        sourceSector: 'arrival_airlock_vestibule',
        destinationSector: 'service_access_elbow',
        type: 'hall',
        x: -52,
        z: -7,
        w: 6,
        d: 8,
        floorY: 0.84,
        ceilingY: 5.6,
        floorSurfaceType: 'shell_service_deck',
        shell: {
          rgb: [20, 56, 68],
          roughness: 0.86,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['north', 'south'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('arrival_service_floor', 0.0, 0.0, 6.0, 7.6, 'shell_service_deck', {
            floorY: 0.84,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('arrival_service_turn_frame', -1.2, -1.4, 1.8, 4.4, 3.4, {
            rgb: [20, 56, 68],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
          }),
          block('arrival_service_lower_hull', 0.0, 0.0, 5.4, 2.6, 6.8, {
            y: -0.78,
            rgb: [12, 30, 38],
            roughness: 0.94,
            emissiveScale: 0.02,
            solid: true,
          }),
        ],
      },
      {
        id: 'public_to_reveal',
        label: 'Exhibit Link',
        sourceSector: 'public_exhibit_spine',
        destinationSector: 'chamber_reveal_gallery',
        type: 'hall',
        x: -36,
        z: 16,
        w: 8,
        d: 8,
        floorY: 1.02,
        ceilingY: 6.2,
        floorSurfaceType: 'viewing_deck',
        shell: {
          rgb: [22, 64, 78],
          roughness: 0.82,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('public_reveal_floor', 0.0, 0.0, 7.6, 7.4, 'viewing_deck', {
            floorY: 1.02,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('public_reveal_side_mask', 1.8, 0.0, 1.8, 4.8, 4.6, {
            rgb: [24, 68, 82],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
        ],
      },
      {
        id: 'service_to_wetpipe',
        label: 'Service Wet Pipe',
        sourceSector: 'service_access_elbow',
        destinationSector: 'wet_pipe_gallery',
        type: 'hall',
        x: -36,
        z: -11,
        w: 8,
        d: 8,
        floorY: 0.82,
        ceilingY: 5.6,
        floorSurfaceType: 'catwalk_grate',
        shell: {
          rgb: [18, 52, 64],
          roughness: 0.88,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('service_wetpipe_floor', 0.0, 0.0, 7.6, 4.8, 'catwalk_grate', {
            floorY: 0.82,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('service_wetpipe_pipe_rack', 0.0, 2.2, 7.0, 0.8, 0.8, {
            y: 3.68,
            rgb: [92, 168, 180],
            roughness: 0.40,
            emissiveScale: 0.05,
          }),
        ],
      },
      {
        id: 'reveal_to_chamber',
        label: 'Reveal Entry Turn',
        sourceSector: 'chamber_reveal_gallery',
        destinationSector: 'main_tank_chamber',
        type: 'doorway',
        x: -16,
        z: 14,
        w: 8,
        d: 10,
        floorY: 1.04,
        ceilingY: 6.6,
        floorSurfaceType: 'viewing_deck',
        shell: {
          rgb: [22, 64, 78],
          roughness: 0.82,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('reveal_chamber_floor', -0.4, -1.2, 7.2, 7.8, 'viewing_deck', {
            floorY: 1.04,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('reveal_chamber_jamb', 2.2, 1.6, 2.0, 5.0, 4.0, {
            rgb: [22, 66, 80],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
        ],
      },
      {
        id: 'wetpipe_to_chamber',
        label: 'Service Chamber Bypass',
        sourceSector: 'wet_pipe_gallery',
        destinationSector: 'main_tank_chamber',
        type: 'hall',
        x: -15,
        z: -2,
        w: 12,
        d: 8,
        floorY: 0.84,
        ceilingY: 5.6,
        floorSurfaceType: 'catwalk_grate',
        shell: {
          rgb: [18, 52, 64],
          roughness: 0.88,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('wetpipe_chamber_walk', 0.0, 0.0, 11.4, 4.8, 'catwalk_grate', {
            floorY: 0.84,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('wetpipe_chamber_upper_rack', -1.4, 2.4, 9.4, 0.8, 0.8, {
            y: 3.68,
            rgb: [96, 170, 182],
            roughness: 0.40,
            emissiveScale: 0.05,
          }),
          block('wetpipe_chamber_lower_hull', 0.0, 0.0, 10.6, 2.6, 4.8, {
            y: -0.74,
            rgb: [12, 30, 36],
            roughness: 0.94,
            emissiveScale: 0.02,
            solid: true,
          }),
        ],
      },
      {
        id: 'wetpipe_to_filtration',
        label: 'Service Filter Bypass',
        sourceSector: 'wet_pipe_gallery',
        destinationSector: 'filtration_core',
        type: 'hall',
        x: 0,
        z: -8,
        w: 22,
        d: 6,
        floorY: 0.82,
        ceilingY: 5.8,
        floorSurfaceType: 'shell_service_deck',
        shell: {
          rgb: [18, 52, 64],
          roughness: 0.88,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('wetpipe_filtration_run', 0.0, 0.0, 21.2, 5.0, 'shell_service_deck', {
            floorY: 0.82,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('wetpipe_filtration_pipebank', 0.0, 2.0, 18.4, 0.8, 0.8, {
            y: 3.62,
            rgb: [92, 166, 178],
            roughness: 0.40,
            emissiveScale: 0.05,
          }),
        ],
      },
      {
        id: 'chamber_to_upper',
        label: 'Observation Ascent',
        sourceSector: 'main_tank_chamber',
        destinationSector: 'upper_observation_bridge',
        type: 'stairs',
        x: 10,
        z: 16,
        w: 8,
        d: 10,
        floorY: 1.14,
        ceilingY: 6.8,
        floorSurfaceType: 'catwalk_grate',
        shell: {
          rgb: [20, 58, 72],
          roughness: 0.82,
          wallThickness: 1.0,
          openSides: ['south', 'north'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('upper_ascent_lower', 0.0, -3.0, 6.2, 3.6, 'wet_service_deck', {
            floorY: 1.18,
            walkableClassification: 'stairs',
            roomSurface: true,
          }),
          surface('upper_ascent_mid', 0.0, 0.0, 6.2, 3.6, 'maintenance_plate', {
            floorY: 2.06,
            walkableClassification: 'stairs',
            roomSurface: true,
          }),
          surface('upper_ascent_upper', 0.0, 3.0, 6.2, 3.6, 'catwalk_grate', {
            floorY: 3.00,
            walkableClassification: 'stairs',
            roomSurface: true,
          }),
        ],
      },
      {
        id: 'chamber_to_filtration',
        label: 'Filtration Descent',
        sourceSector: 'main_tank_chamber',
        destinationSector: 'filtration_core',
        type: 'ramp',
        x: 10,
        z: -2,
        w: 8,
        d: 12,
        floorY: 1.00,
        ceilingY: 6.0,
        floorSurfaceType: 'maintenance_ramp',
        shell: {
          rgb: [20, 56, 68],
          roughness: 0.86,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['north', 'south'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('filtration_descent_upper', 0.0, -3.4, 6.4, 3.8, 'wet_service_deck', {
            floorY: 1.00,
            walkableClassification: 'ramp',
            roomSurface: true,
          }),
          surface('filtration_descent_mid', 0.0, 0.0, 6.4, 3.8, 'maintenance_plate', {
            floorY: 0.90,
            walkableClassification: 'ramp',
            roomSurface: true,
          }),
          surface('filtration_descent_lower', 0.0, 3.4, 6.4, 3.8, 'maintenance_plate', {
            floorY: 0.82,
            walkableClassification: 'ramp',
            roomSurface: true,
          }),
        ],
      },
      {
        id: 'filtration_to_trench',
        label: 'Trench Drop',
        sourceSector: 'filtration_core',
        destinationSector: 'flooded_maintenance_trench',
        type: 'stairs',
        x: 18,
        z: -10,
        w: 8,
        d: 8,
        floorY: 0.72,
        ceilingY: 5.2,
        floorSurfaceType: 'maintenance_ramp',
        shell: {
          rgb: [18, 50, 60],
          roughness: 0.88,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['north', 'south'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('trench_drop_upper', 0.0, -2.4, 6.2, 2.8, 'wet_service_deck', {
            floorY: 0.72,
            walkableClassification: 'stairs',
            roomSurface: true,
          }),
          surface('trench_drop_mid', 0.0, 0.0, 6.2, 2.8, 'maintenance_plate', {
            floorY: 0.46,
            walkableClassification: 'stairs',
            roomSurface: true,
          }),
          surface('trench_drop_lower', 0.0, 2.4, 6.2, 3.0, 'maintenance_channel', {
            floorY: 0.22,
            walkableClassification: 'stairs',
            roomSurface: true,
          }),
        ],
      },
      {
        id: 'upper_to_pump',
        label: 'Observation Return',
        sourceSector: 'upper_observation_bridge',
        destinationSector: 'pump_gallery_rejoin',
        type: 'hall',
        x: 28,
        z: 11,
        w: 8,
        d: 16,
        floorY: 3.00,
        ceilingY: 6.4,
        floorSurfaceType: 'catwalk_grate',
        shell: {
          rgb: [20, 56, 70],
          roughness: 0.82,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['north', 'south'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('upper_return_north', 0.0, -4.8, 5.8, 3.4, 'catwalk_grate', {
            floorY: 3.00,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
          surface('upper_return_mid', 0.0, 0.0, 5.8, 3.4, 'maintenance_plate', {
            floorY: 2.06,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
          surface('upper_return_south', 0.0, 4.8, 6.0, 3.6, 'shell_service_deck', {
            floorY: 1.18,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('upper_return_side_machine', 2.6, 0.8, 2.0, 3.6, 5.0, {
            rgb: [28, 68, 80],
            roughness: 0.80,
            emissiveScale: 0.03,
            solid: true,
          }),
        ],
      },
      {
        id: 'trench_to_pump',
        label: 'Pump Rise',
        sourceSector: 'flooded_maintenance_trench',
        destinationSector: 'pump_gallery_rejoin',
        type: 'stairs',
        x: 28,
        z: -12,
        w: 10,
        d: 8,
        floorY: 0.44,
        ceilingY: 5.2,
        floorSurfaceType: 'maintenance_rise',
        shell: {
          rgb: [18, 48, 58],
          roughness: 0.88,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('pump_rise_lower', -2.4, 0.0, 4.6, 4.4, 'maintenance_channel', {
            floorY: 0.44,
            walkableClassification: 'stairs',
            roomSurface: true,
          }),
          surface('pump_rise_mid', 0.8, 0.0, 4.8, 4.4, 'maintenance_plate', {
            floorY: 0.74,
            walkableClassification: 'stairs',
            roomSurface: true,
          }),
          surface('pump_rise_upper', 3.6, 0.0, 4.2, 4.4, 'shell_service_deck', {
            floorY: 1.02,
            walkableClassification: 'stairs',
            roomSurface: true,
          }),
        ],
      },
      {
        id: 'pump_to_compression',
        label: 'Nursery Compression',
        sourceSector: 'pump_gallery_rejoin',
        destinationSector: 'nursery_compression_hall',
        type: 'hall',
        x: 44,
        z: 5,
        w: 8,
        d: 14,
        floorY: 1.06,
        ceilingY: 5.8,
        floorSurfaceType: 'shell_service_deck',
        shell: {
          rgb: [20, 60, 74],
          roughness: 0.84,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('pump_compression_floor', 0.0, 0.0, 7.4, 10.8, 'shell_service_deck', {
            floorY: 1.06,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('pump_compression_jamb', 1.6, 1.8, 1.8, 4.6, 3.8, {
            rgb: [22, 64, 78],
            roughness: 0.84,
            emissiveScale: 0.03,
            solid: true,
          }),
        ],
      },
      {
        id: 'compression_to_final',
        label: 'Nursery Final Threshold',
        sourceSector: 'nursery_compression_hall',
        destinationSector: 'nursery_recovery_alcove',
        type: 'doorway',
        x: 54,
        z: 17,
        w: 8,
        d: 14,
        floorY: 1.42,
        ceilingY: 5.8,
        floorSurfaceType: 'viewing_deck',
        shell: {
          rgb: [22, 66, 80],
          roughness: 0.82,
          wallThickness: 1.0,
          floorSkirt: 0.56,
          openSides: ['south', 'north'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('compression_final_lower', -1.4, -3.2, 6.4, 4.4, 'shell_service_deck', {
            floorY: 1.42,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('compression_final_upper', 1.4, 2.8, 6.0, 4.4, 'viewing_deck', {
            floorY: 1.68,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
      },
    ],
  },

  coins: [
    { x: -62.6, y: 0, z: 0.8 },
    { x: -54.0, y: 0, z: 6.0 },
    { x: -46.8, y: 0, z: 14.8 },
    { x: -38.8, y: 0, z: 17.8 },
    { x: -44.2, y: 0, z: -13.0 },
    { x: -29.8, y: 0, z: -10.0 },
    { x: -24.0, y: 0, z: 20.0 },
    { x: -12.6, y: 0, z: 11.4 },
    { x: 1.6, y: 0, z: 18.2 },
    { x: 9.8, y: 0, z: 10.6 },
    { x: 9.6, y: 0, z: -1.2 },
    { x: 19.2, y: 0, z: -3.8 },
    { x: 18.2, y: 0, z: -17.0 },
    { x: 16.6, y: 0, z: 18.2 },
    { x: 30.0, y: 0, z: 10.8 },
    { x: 38.4, y: 0, z: -5.2 },
    { x: 48.2, y: 0, z: 9.0 },
    { x: 59.2, y: 0, z: 23.0 },
  ],

  currents: [
    { name: 'current_touch_pool', x: -38.4, y: 2.02, z: 9.0, w: 6.4, h: 4.0, d: 5.2, pushX: 0.6, pushZ: 1.0 },
    { name: 'current_chamber_tank', x: 12.6, y: 2.48, z: 13.8, w: 8.2, h: 4.4, d: 6.6, pushX: 1.2, pushZ: -0.6 },
    { name: 'current_trench_backwash', x: 18.2, y: 1.48, z: -18.0, w: 8.8, h: 4.0, d: 6.4, pushX: 1.6, pushZ: 0.4 },
  ],

  deepWaterPockets: [
    { name: 'touch_pool_pocket', x: -38.2, y: 2.04, z: 8.8, w: 6.8, h: 4.6, d: 5.8 },
    { name: 'chamber_viewing_pocket', x: 12.8, y: 2.46, z: 13.8, w: 9.4, h: 5.0, d: 7.0 },
    { name: 'filtration_basin_pocket', x: 21.8, y: 2.02, z: -1.2, w: 7.0, h: 5.4, d: 6.0 },
    { name: 'trench_flood_pocket', x: 18.0, y: 1.50, z: -18.2, w: 9.2, h: 4.6, d: 6.8 },
  ],

  airBubblePickups: [
    { name: 'bubble_chamber', x: 12.4, y: 2.56, z: 13.8, radius: 0.82, refill: 8 },
    { name: 'bubble_filtration', x: 21.6, y: 2.12, z: -1.2, radius: 0.82, refill: 10 },
    { name: 'bubble_trench', x: 18.0, y: 1.62, z: -18.0, radius: 0.82, refill: 10 },
  ],

  eelRails: [
    { name: 'eel_spill_gate', x1: 17.0, y1: 1.12, x2: 24.4, y2: 1.12, z: -1.2, phaseOffset: 0.12 },
    { name: 'eel_upper_bridge', x1: 12.2, y1: 3.26, x2: 19.8, y2: 3.26, z: 20.4, phaseOffset: 0.44 },
  ],

  vents: [
    { name: 'vent_filtration_lift', x: 20.8, y: 0.44, z: -5.2, w: 2.0, h: 3.6, liftVy: 15.8, phaseOffset: 0.18 },
    { name: 'vent_trench_lift', x: 18.0, y: 0.12, z: -18.0, w: 2.0, h: 3.4, liftVy: 16.0, phaseOffset: 0.56 },
  ],

  jellyfish: [
    { name: 'jelly_touch_pool', x: -38.2, y: 2.02, z: 8.8, bounds: { minX: -41.4, maxX: -35.0, minY: 1.4, maxY: 3.2, minZ: 6.6, maxZ: 11.2 }, speed: 0.78, turnSpeed: 2.2 },
    { name: 'jelly_chamber_a', x: 10.8, y: 2.34, z: 14.0, bounds: { minX: 7.0, maxX: 14.8, minY: 1.6, maxY: 3.8, minZ: 11.2, maxZ: 17.6 }, speed: 0.94, turnSpeed: 2.5 },
    { name: 'jelly_chamber_b', x: 15.8, y: 2.12, z: 7.8, bounds: { minX: 12.0, maxX: 18.8, minY: 1.4, maxY: 3.6, minZ: 5.4, maxZ: 10.8 }, speed: 0.98, turnSpeed: 2.6 },
    { name: 'jelly_filtration', x: 21.4, y: 2.00, z: -1.4, bounds: { minX: 18.2, maxX: 24.6, minY: 1.2, maxY: 3.8, minZ: -3.8, maxZ: 1.2 }, speed: 1.00, turnSpeed: 2.7 },
    { name: 'jelly_trench', x: 18.2, y: 1.48, z: -18.0, bounds: { minX: 13.8, maxX: 22.6, minY: 0.9, maxY: 2.8, minZ: -20.8, maxZ: -15.4 }, speed: 1.04, turnSpeed: 2.8 },
  ],

  signage: [
    { x: -45.0, y: 5.2, z: 21.6, text: 'GUEST GALLERY', width: 5.8, height: 1.5 },
    { x: -42.6, y: 4.6, z: -17.0, text: 'STAFF ONLY', width: 4.8, height: 1.4 },
    { x: 18.6, y: 5.2, z: -8.8, text: 'FILTRATION SPILL GATE', width: 7.0, height: 1.5 },
    { x: 58.2, y: 5.6, z: 31.0, text: 'RECOVERY NURSERY', width: 6.6, height: 1.5 },
  ],

  decorPlanes: [
    { name: 'arrival_fish_shadow', x: -63.8, y: 5.2, z: 6.8, width: 6.4, height: 1.6, rotationY: 0.08, rgb: [10, 28, 36], emissiveScale: 0.03, alpha: 0.16 },
    { name: 'public_school_shadow', x: -44.2, y: 6.2, z: 21.4, width: 12.0, height: 2.4, rotationY: -0.08, rgb: [10, 24, 34], emissiveScale: 0.03, alpha: 0.18 },
    { name: 'chamber_creature_shadow', x: 2.4, y: 8.4, z: 22.8, width: 16.0, height: 4.0, rotationY: -0.06, rgb: [8, 22, 30], emissiveScale: 0.03, alpha: 0.16 },
    { name: 'chamber_caustic_band', x: 0.8, y: 9.4, z: 19.8, width: 22.0, height: 3.8, rgb: [126, 214, 226], emissiveScale: 0.12, alpha: 0.09 },
    { name: 'nursery_fish_shadow', x: 58.2, y: 6.6, z: 27.8, width: 8.8, height: 1.8, rotationY: 0.10, rgb: [10, 28, 36], emissiveScale: 0.03, alpha: 0.16 },
  ],

  decorBlocks: [
    { name: 'arrival_exterior_shell', x: -60.0, y: 3.2, z: 0.0, w: 18.0, h: 6.2, d: 14.0, rgb: [18, 44, 56], emissiveScale: 0.02, roughness: 0.92, solid: true },
    { name: 'fork_split_spine', x: -50.0, y: 3.2, z: 0.0, w: 3.0, h: 5.4, d: 11.4, rgb: [20, 58, 72], emissiveScale: 0.03, roughness: 0.86, solid: true },
    { name: 'fork_north_portal_mass', x: -47.6, y: 3.2, z: 6.4, w: 4.4, h: 5.0, d: 2.4, rgb: [20, 58, 72], emissiveScale: 0.03, roughness: 0.84, solid: true },
    { name: 'fork_south_portal_mass', x: -47.6, y: 3.2, z: -6.4, w: 4.4, h: 5.0, d: 2.4, rgb: [20, 54, 66], emissiveScale: 0.03, roughness: 0.84, solid: true },
    { name: 'public_north_housing', x: -44.0, y: 4.6, z: 22.8, w: 22.0, h: 7.0, d: 6.2, rgb: [20, 58, 72], emissiveScale: 0.03, roughness: 0.88, solid: true },
    { name: 'service_south_housing', x: -32.0, y: 4.0, z: -20.4, w: 28.0, h: 6.6, d: 6.0, rgb: [18, 48, 60], emissiveScale: 0.03, roughness: 0.90, solid: true },
    { name: 'chamber_east_housing', x: 12.0, y: 4.8, z: 26.4, w: 20.0, h: 7.4, d: 6.4, rgb: [20, 58, 72], emissiveScale: 0.03, roughness: 0.88, solid: true },
    { name: 'chamber_service_annex', x: 9.6, y: 3.2, z: -10.8, w: 16.0, h: 5.2, d: 5.2, rgb: [20, 56, 70], emissiveScale: 0.03, roughness: 0.88, solid: true },
    { name: 'pump_annex_housing', x: 39.6, y: 4.4, z: -14.6, w: 14.0, h: 7.0, d: 5.6, rgb: [20, 58, 72], emissiveScale: 0.03, roughness: 0.88, solid: true },
    { name: 'nursery_outer_housing', x: 58.2, y: 4.6, z: 32.8, w: 18.0, h: 7.0, d: 6.0, rgb: [22, 66, 82], emissiveScale: 0.03, roughness: 0.86, solid: true },
    { name: 'nursery_goal_shell', x: 61.0, y: 4.6, z: 24.8, w: 8.4, h: 6.2, d: 8.4, rgb: [22, 70, 84], emissiveScale: 0.03, roughness: 0.84, solid: true },
  ],

  decorColumns: [
    { name: 'chamber_support_pillar_w', x: -13.4, y: 4.4, z: 16.0, diameter: 1.4, height: 8.2, rgb: [84, 180, 198], emissiveScale: 0.06, roughness: 0.42, alpha: 0.28, solid: true },
    { name: 'chamber_support_pillar_e', x: 13.2, y: 4.6, z: 17.8, diameter: 1.4, height: 8.6, rgb: [84, 180, 198], emissiveScale: 0.06, roughness: 0.42, alpha: 0.28, solid: true },
    { name: 'nursery_recovery_pod', x: 58.0, y: 4.2, z: 27.4, diameter: 5.2, height: 5.8, rgb: [94, 198, 214], emissiveScale: 0.08, roughness: 0.30, alpha: 0.24, solid: true },
  ],

  decorPlatforms: [],
});

export const LEVEL5 = {
  ...BASE_LEVEL5,
  coins: normalizeCoinsOnSurfaces(BASE_LEVEL5, { defaultZ: 0 }),
};
