import { normalizeCoinsOnSurfaces } from './eraLevelLayout.js';
import { compileAuthoredEraLayout } from './eraAuthoredLayout.js';

function surface(id, offsetX, offsetZ, w, d, surfaceType, extra = {}) {
  return {
    id,
    offsetX,
    offsetZ,
    w,
    d,
    h: extra.h ?? 0.52,
    surfaceType,
    ...extra,
  };
}

function block(name, offsetX, offsetZ, w, h, d, extra = {}) {
  return {
    name,
    offsetX,
    offsetZ,
    w,
    h,
    d,
    ...extra,
  };
}

function column(name, offsetX, offsetZ, diameter, height, extra = {}) {
  return {
    name,
    offsetX,
    offsetZ,
    diameter,
    height,
    ...extra,
  };
}

function platform(name, offsetX, offsetZ, w, h, d, extra = {}) {
  return {
    name,
    offsetX,
    offsetZ,
    w,
    h,
    d,
    ...extra,
  };
}

const LEVEL5_CAMERA_PRESETS = {
  standard: {
    id: 'standard',
    label: 'Standard',
    distance: 6.6,
    height: 3.2,
    focusHeight: 1.12,
    lookAhead: 2.8,
    fov: 0.96,
  },
  closer: {
    id: 'closer',
    label: 'Closer Over-Shoulder',
    distance: 5.4,
    height: 2.7,
    focusHeight: 1.06,
    lookAhead: 2.2,
    fov: 1.0,
  },
};

const BASE_LEVEL5 = compileAuthoredEraLayout({
  totalCollectibles: 18,
  spawnYaw: 0.02,
  defaultCameraPreset: 'closer',
  cameraPresets: LEVEL5_CAMERA_PRESETS,
  spawn: { x: -40.0, y: 1.28, z: 0.0 },
  goal: { x: 47.6, y: 1.58, z: 8.8 },
  theme: 'aquarium',
  showGroundVisual: false,
  showRouteRibbons: false,
  disableDecorOcclusionFade: true,
  respawnAnchors: [
    {
      id: 'level5_spawn_anchor',
      label: 'Arrival Vestibule',
      x: -40.0,
      y: 1.28,
      z: 0.0,
      spaceId: 'arrival_vestibule',
      allowedReason: 'spawn',
    },
    {
      id: 'cp_public_spine',
      checkpointId: 'cp_public_spine',
      label: 'Public Exhibit Hall',
      x: -19.0,
      y: 1.40,
      z: 11.8,
      spaceId: 'public_exhibit_hall',
      allowedReason: 'checkpoint',
    },
    {
      id: 'cp_hero_chamber',
      checkpointId: 'cp_hero_chamber',
      label: 'Hero Tank Chamber',
      x: 5.2,
      y: 1.48,
      z: 8.4,
      spaceId: 'hero_tank_chamber',
      allowedReason: 'checkpoint',
    },
    {
      id: 'cp_filtration_core',
      checkpointId: 'cp_filtration_core',
      label: 'Filtration Hazard Room',
      x: 24.8,
      y: 1.36,
      z: -1.8,
      spaceId: 'filtration_hazard_room',
      allowedReason: 'checkpoint',
    },
  ],
  acts: [
    { id: 'A', label: 'Arrival And Fork', range: [-44, -22] },
    { id: 'B', label: 'Exhibit And Chamber', range: [-22, 18] },
    { id: 'C', label: 'Filtration And Nursery', range: [18, 54] },
  ],
  authoredMap: {
    id: 'aquarium-drift-map05-restart',
    startSector: 'arrival_vestibule',
    goalSector: 'nursery_goal_room',
    sectors: [
      {
        id: 'arrival_vestibule',
        label: 'Arrival Vestibule',
        x: -36,
        z: 0,
        w: 14,
        d: 14,
        floorY: 0.84,
        ceilingY: 5.8,
        floorSurfaceType: 'wet_service_deck',
        wallLanguage: 'arrival_airlock',
        landmarks: ['arrival tank', 'fork bulkhead'],
        shell: {
          rgb: [24, 64, 80],
          roughness: 0.84,
          wallThickness: 1.1,
          floorSkirt: 0.56,
          openSides: ['east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('arrival_floor', -0.6, 0.0, 10.8, 8.8, 'wet_service_deck', {
            floorY: 0.84,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('arrival_public_pad', 3.6, 2.8, 3.0, 3.0, 'viewing_deck', {
            floorY: 0.88,
            walkableClassification: 'guest-bay',
            roomSurface: true,
          }),
          surface('arrival_service_pad', 3.6, -2.8, 3.0, 3.0, 'shell_service_deck', {
            floorY: 0.84,
            walkableClassification: 'service-bay',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('arrival_display_wall', -4.4, 3.8, 5.6, 4.8, 0.8, {
            rgb: [70, 170, 192],
            emissiveScale: 0.10,
            roughness: 0.34,
            alpha: 0.80,
            solid: true,
            interiorVisible: true,
          }),
          block('arrival_display_volume', -4.4, 6.2, 5.2, 4.2, 4.0, {
            rgb: [22, 88, 114],
            emissiveScale: 0.04,
            roughness: 0.34,
            alpha: 0.22,
            interiorVisible: true,
          }),
          block('arrival_fork_bulkhead', 2.8, 0.0, 3.4, 5.0, 8.8, {
            rgb: [24, 66, 82],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'route-divider',
          }),
          block('arrival_public_jamb', 5.0, 2.8, 1.6, 4.4, 2.8, {
            rgb: [22, 60, 74],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'portal-frame',
          }),
          block('arrival_service_jamb', 5.0, -2.8, 1.6, 4.4, 2.8, {
            rgb: [22, 58, 72],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'portal-frame',
          }),
          block('arrival_portal_header', 4.1, 0.0, 3.0, 0.52, 8.6, {
            y: 4.92,
            rgb: [20, 56, 70],
            roughness: 0.86,
            emissiveScale: 0.03,
          }),
          block('arrival_orientation_kiosk', -6.2, -2.0, 2.4, 2.0, 1.6, {
            rgb: [78, 110, 122],
            roughness: 0.78,
            emissiveScale: 0.03,
          }),
          block('arrival_north_baffle', -0.8, 5.0, 6.2, 4.4, 1.2, {
            rgb: [18, 54, 68],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'arrival-baffle',
          }),
          block('arrival_south_baffle', -2.2, -4.8, 4.2, 4.0, 1.2, {
            rgb: [18, 50, 62],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'arrival-baffle',
          }),
          block('arrival_east_upper_wall', 6.4, 0.0, 1.2, 4.8, 2.0, {
            rgb: [18, 54, 66],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'portal-edge',
          }),
        ],
        decorColumns: [
          column('arrival_display_post_l', -6.8, 3.8, 0.62, 5.4, {
            rgb: [90, 186, 206],
            roughness: 0.48,
          }),
          column('arrival_display_post_r', -2.0, 3.8, 0.62, 5.4, {
            rgb: [90, 186, 206],
            roughness: 0.48,
          }),
        ],
        decorPlatforms: [
          platform('arrival_ceiling_canopy', -2.6, 0.0, 7.6, 0.34, 9.6, {
            y: 4.82,
            rgb: [18, 54, 66],
            roughness: 0.86,
            emissiveScale: 0.03,
            structuralShell: true,
          }),
          platform('arrival_entry_header', -6.0, 0.0, 3.4, 0.30, 10.4, {
            y: 4.28,
            rgb: [20, 62, 78],
            roughness: 0.82,
            emissiveScale: 0.04,
            structuralShell: true,
          }),
        ],
        signage: [
          {
            offsetX: -0.6,
            y: 4.9,
            offsetZ: -5.2,
            text: 'ARRIVAL AIRLOCK',
            width: 7.4,
            height: 1.6,
          },
        ],
      },
      {
        id: 'public_exhibit_hall',
        label: 'Public Exhibit Hall',
        x: -18,
        z: 12,
        w: 16,
        d: 12,
        floorY: 0.96,
        ceilingY: 6.0,
        floorSurfaceType: 'viewing_deck',
        wallLanguage: 'public_gallery',
        landmarks: ['north viewing tank', 'touch pool'],
        shell: {
          rgb: [24, 70, 86],
          roughness: 0.82,
          wallThickness: 1.1,
          floorSkirt: 0.54,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('public_main_walk', -0.8, -0.2, 12.4, 7.6, 'viewing_deck', {
            floorY: 0.96,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('public_viewing_bay', -0.2, 4.0, 11.4, 2.8, 'exhibit_deck', {
            floorY: 1.00,
            walkableClassification: 'guest-bay',
            roomSurface: true,
          }),
          surface('public_touch_pool_apron', 4.8, -2.8, 4.2, 3.0, 'exhibit_deck', {
            floorY: 1.00,
            walkableClassification: 'teaching-apron',
            roomSurface: true,
          }),
        ],
        checkpoints: [
          {
            id: 'cp_public_spine',
            anchorId: 'cp_public_spine',
            offsetX: 0.0,
            offsetZ: 0.8,
            label: 'Public Exhibit Hall',
          },
        ],
        decorBlocks: [
          block('public_tank_wall', -0.2, 5.8, 13.8, 5.8, 0.9, {
            rgb: [82, 190, 210],
            emissiveScale: 0.10,
            roughness: 0.34,
            alpha: 0.82,
            solid: true,
            interiorVisible: true,
          }),
          block('public_tank_volume', -0.2, 8.8, 13.0, 5.2, 4.8, {
            rgb: [24, 96, 122],
            emissiveScale: 0.04,
            roughness: 0.32,
            alpha: 0.22,
            interiorVisible: true,
          }),
          block('public_tank_backdrop', -0.2, 11.8, 12.6, 5.4, 2.2, {
            rgb: [10, 34, 42],
            emissiveScale: 0.02,
            roughness: 0.92,
            solid: true,
            structuralShell: true,
            blockerReason: 'tank-backdrop',
          }),
          block('public_touch_pool_backwall', 5.0, -4.8, 4.8, 2.8, 0.8, {
            rgb: [18, 48, 58],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'touch-pool-boundary',
          }),
          block('public_touch_pool_volume', 5.0, -6.6, 4.2, 2.8, 3.6, {
            rgb: [24, 92, 120],
            roughness: 0.34,
            emissiveScale: 0.04,
            alpha: 0.24,
            interiorVisible: true,
          }),
          block('public_chamber_screen', 4.6, 0.8, 2.6, 4.8, 8.2, {
            rgb: [20, 56, 68],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'route-divider',
          }),
          block('public_chamber_header', 6.2, 0.8, 2.2, 0.52, 5.8, {
            y: 5.10,
            rgb: [20, 54, 66],
            roughness: 0.86,
            emissiveScale: 0.03,
          }),
          block('public_info_wall', -5.6, -2.2, 2.6, 2.4, 1.0, {
            rgb: [74, 112, 126],
            roughness: 0.76,
            emissiveScale: 0.03,
          }),
          block('public_touch_pool_rail_n', 5.0, -4.4, 5.0, 0.72, 0.24, {
            y: 1.38,
            rgb: [154, 226, 238],
            roughness: 0.42,
            emissiveScale: 0.10,
            alpha: 0.84,
            interiorVisible: true,
          }),
          block('public_touch_pool_rail_e', 7.4, -5.6, 0.24, 0.72, 3.2, {
            y: 1.38,
            rgb: [154, 226, 238],
            roughness: 0.42,
            emissiveScale: 0.10,
            alpha: 0.84,
            interiorVisible: true,
          }),
          block('public_touch_pool_rail_w', 2.6, -5.6, 0.24, 0.72, 3.2, {
            y: 1.38,
            rgb: [154, 226, 238],
            roughness: 0.42,
            emissiveScale: 0.10,
            alpha: 0.84,
            interiorVisible: true,
          }),
          block('public_gallery_niche', -4.6, 0.8, 2.2, 4.0, 3.4, {
            rgb: [18, 50, 62],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'gallery-niche',
          }),
          block('public_viewer_bench', -2.2, 1.8, 2.8, 0.58, 1.0, {
            y: 1.20,
            rgb: [66, 96, 104],
            roughness: 0.74,
            emissiveScale: 0.03,
          }),
        ],
        decorColumns: [
          column('public_tank_frame_l', -6.6, 5.8, 0.70, 5.8, {
            rgb: [92, 198, 214],
            roughness: 0.44,
          }),
          column('public_tank_frame_r', 6.2, 5.8, 0.70, 5.8, {
            rgb: [92, 198, 214],
            roughness: 0.44,
          }),
        ],
        decorPlatforms: [
          platform('public_gallery_canopy', -1.0, 0.8, 11.8, 0.34, 7.4, {
            y: 4.92,
            rgb: [18, 54, 66],
            roughness: 0.84,
            emissiveScale: 0.03,
            structuralShell: true,
          }),
          platform('public_tank_cap', -0.2, 5.8, 13.8, 0.28, 1.0, {
            y: 4.96,
            rgb: [90, 198, 214],
            roughness: 0.34,
            emissiveScale: 0.10,
          }),
        ],
        signage: [
          {
            offsetX: -0.8,
            y: 5.1,
            offsetZ: -4.6,
            text: 'PUBLIC EXHIBIT HALL',
            width: 8.2,
            height: 1.6,
          },
        ],
      },
      {
        id: 'service_elbow',
        label: 'Service Elbow',
        x: -18,
        z: -6,
        w: 14,
        d: 10,
        floorY: 0.88,
        ceilingY: 5.4,
        floorSurfaceType: 'catwalk_grate',
        wallLanguage: 'service_hall',
        landmarks: ['pipe manifold', 'staff partition'],
        shell: {
          rgb: [20, 58, 72],
          roughness: 0.88,
          wallThickness: 1.1,
          floorSkirt: 0.50,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('service_main_walk', -0.4, 0.0, 10.2, 4.4, 'catwalk_grate', {
            floorY: 0.88,
            walkableClassification: 'service-floor',
            roomSurface: true,
          }),
          surface('service_manifold_bay', 3.8, 2.0, 4.8, 3.2, 'maintenance_plate', {
            floorY: 0.92,
            walkableClassification: 'service-bay',
            roomSurface: true,
          }),
          surface('service_dry_strip', -0.8, -2.4, 8.8, 2.6, 'shell_service_deck', {
            floorY: 0.88,
            walkableClassification: 'dry-edge',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('service_pipe_bank', 0.0, 3.6, 10.8, 2.8, 0.8, {
            rgb: [18, 50, 62],
            roughness: 0.90,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'pipe-bank',
          }),
          block('service_manifold', 4.4, 0.8, 3.2, 4.2, 4.0, {
            rgb: [40, 88, 102],
            roughness: 0.76,
            emissiveScale: 0.04,
            solid: true,
            blockerReason: 'machine-bank',
          }),
          block('service_partition', 1.8, -0.8, 2.2, 4.0, 4.8, {
            rgb: [18, 50, 62],
            roughness: 0.90,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'route-divider',
          }),
          block('service_cable_tray', -3.8, 3.0, 4.8, 0.44, 1.2, {
            y: 4.68,
            rgb: [24, 64, 76],
            roughness: 0.86,
            emissiveScale: 0.03,
          }),
          block('service_west_portal_mass', -5.2, 0.0, 1.8, 4.6, 6.2, {
            rgb: [16, 48, 60],
            roughness: 0.90,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'portal-edge',
          }),
          block('service_east_portal_mass', 5.2, 1.6, 1.8, 4.8, 5.0, {
            rgb: [16, 48, 60],
            roughness: 0.90,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'portal-edge',
          }),
          block('service_turn_baffle', -0.6, -2.0, 3.4, 3.8, 1.0, {
            rgb: [18, 52, 62],
            roughness: 0.90,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'route-turn',
          }),
        ],
        decorPlatforms: [
          platform('service_plenum_cover', -0.6, 0.2, 9.4, 0.30, 4.4, {
            y: 4.46,
            rgb: [18, 52, 64],
            roughness: 0.88,
            emissiveScale: 0.03,
            structuralShell: true,
          }),
        ],
        signage: [
          {
            offsetX: -0.2,
            y: 4.7,
            offsetZ: -3.8,
            text: 'STAFF ACCESS',
            width: 5.8,
            height: 1.4,
          },
        ],
      },
      {
        id: 'hero_tank_chamber',
        label: 'Hero Tank Chamber',
        x: 6,
        z: 8,
        w: 24,
        d: 18,
        floorY: 1.02,
        ceilingY: 7.0,
        floorSurfaceType: 'viewing_deck',
        wallLanguage: 'hero_tank_chamber',
        landmarks: ['dominant tank wall', 'filtration tower'],
        shell: {
          rgb: [22, 64, 80],
          roughness: 0.84,
          wallThickness: 1.2,
          floorSkirt: 0.56,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('chamber_concourse', -6.2, 1.6, 7.4, 6.4, 'viewing_deck', {
            floorY: 1.02,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('chamber_main_floor', 2.0, 1.2, 10.8, 8.2, 'viewing_deck', {
            floorY: 1.02,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('chamber_service_edge', 1.2, -5.0, 10.0, 2.8, 'shell_service_deck', {
            floorY: 0.98,
            walkableClassification: 'service-floor',
            roomSurface: true,
          }),
          surface('chamber_machine_apron', 8.4, 1.6, 4.6, 6.2, 'exhibit_deck', {
            floorY: 1.06,
            walkableClassification: 'machine-apron',
            roomSurface: true,
          }),
        ],
        checkpoints: [
          {
            id: 'cp_hero_chamber',
            anchorId: 'cp_hero_chamber',
            offsetX: -0.6,
            offsetZ: 0.8,
            label: 'Hero Tank Chamber',
          },
        ],
        decorBlocks: [
          block('chamber_reveal_screen', -5.2, 2.0, 2.0, 5.4, 8.4, {
            rgb: [18, 52, 64],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'reveal-screen',
          }),
          block('chamber_west_north_edge', -11.0, 5.8, 1.8, 6.0, 5.4, {
            rgb: [16, 46, 58],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'room-boundary',
          }),
          block('chamber_west_south_edge', -11.0, -1.2, 1.8, 6.0, 5.2, {
            rgb: [16, 46, 58],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'room-boundary',
          }),
          block('chamber_entry_header', -8.6, 2.0, 3.2, 0.52, 5.0, {
            y: 5.22,
            rgb: [18, 54, 66],
            roughness: 0.86,
            emissiveScale: 0.03,
          }),
          block('chamber_tank_wall', -0.4, 7.0, 15.8, 6.6, 1.0, {
            rgb: [86, 198, 218],
            emissiveScale: 0.10,
            roughness: 0.32,
            alpha: 0.82,
            solid: true,
            interiorVisible: true,
          }),
          block('chamber_tank_volume', -0.4, 10.6, 15.2, 6.2, 7.6, {
            rgb: [24, 96, 124],
            emissiveScale: 0.04,
            roughness: 0.32,
            alpha: 0.22,
            interiorVisible: true,
          }),
          block('chamber_tank_base', -0.4, 10.6, 16.0, 1.8, 8.0, {
            y: 0.96,
            rgb: [18, 48, 58],
            roughness: 0.92,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'tank-base',
          }),
          block('chamber_landmark_machine', 9.0, 1.6, 4.2, 6.6, 8.6, {
            rgb: [54, 116, 132],
            roughness: 0.70,
            emissiveScale: 0.05,
            solid: true,
            blockerReason: 'machine-bank',
          }),
          block('chamber_east_backwall', 11.0, 7.4, 3.2, 6.0, 9.0, {
            rgb: [18, 52, 64],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'room-boundary',
          }),
          block('chamber_south_service_divider', 0.2, -2.4, 10.8, 3.2, 1.0, {
            rgb: [18, 50, 62],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'route-divider',
          }),
          block('chamber_backwall_north', 0.0, 15.8, 20.8, 6.4, 1.2, {
            rgb: [16, 46, 56],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'room-boundary',
          }),
          block('chamber_south_west_wall', -6.0, -7.0, 10.4, 5.6, 1.2, {
            rgb: [16, 46, 58],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'room-boundary',
          }),
          block('chamber_south_east_wall', 8.8, -7.0, 6.4, 5.6, 1.2, {
            rgb: [16, 46, 58],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'room-boundary',
          }),
          block('chamber_tank_backdrop', -0.4, 13.6, 14.8, 6.0, 3.0, {
            rgb: [10, 34, 42],
            roughness: 0.92,
            emissiveScale: 0.02,
            solid: true,
            structuralShell: true,
            blockerReason: 'tank-backdrop',
          }),
          block('chamber_machine_wing', 10.8, -1.6, 2.2, 5.8, 5.4, {
            rgb: [24, 72, 86],
            roughness: 0.78,
            emissiveScale: 0.04,
            solid: true,
            structuralShell: true,
            blockerReason: 'machine-wing',
          }),
          block('chamber_service_guard', 0.8, -3.6, 9.4, 1.2, 0.38, {
            y: 1.54,
            rgb: [132, 178, 186],
            roughness: 0.50,
            emissiveScale: 0.05,
            alpha: 0.92,
          }),
        ],
        decorColumns: [
          column('chamber_tank_frame_l', -8.0, 7.0, 0.72, 6.8, {
            rgb: [94, 202, 218],
            roughness: 0.44,
          }),
          column('chamber_tank_frame_r', 7.2, 7.0, 0.72, 6.8, {
            rgb: [94, 202, 218],
            roughness: 0.44,
          }),
          column('chamber_filter_stack_a', 8.6, 4.8, 1.6, 7.2, {
            rgb: [72, 144, 162],
            roughness: 0.58,
          }),
          column('chamber_filter_stack_b', 10.6, 6.2, 1.2, 6.4, {
            rgb: [86, 168, 186],
            roughness: 0.54,
          }),
          column('chamber_bridge_post_w', -0.8, 4.4, 0.46, 4.4, {
            rgb: [66, 118, 132],
            roughness: 0.64,
          }),
          column('chamber_bridge_post_e', 4.4, 4.4, 0.46, 4.4, {
            rgb: [66, 118, 132],
            roughness: 0.64,
          }),
        ],
        decorPlatforms: [
          platform('chamber_observation_bridge', 1.8, 4.4, 7.0, 0.28, 1.8, {
            y: 4.68,
            rgb: [54, 104, 118],
            roughness: 0.70,
            emissiveScale: 0.04,
          }),
          platform('chamber_canopy_north', -1.0, 8.6, 13.6, 0.34, 4.2, {
            y: 5.86,
            rgb: [20, 56, 68],
            roughness: 0.84,
            emissiveScale: 0.03,
            structuralShell: true,
          }),
          platform('chamber_canopy_entry', -7.2, 2.0, 4.8, 0.30, 6.4, {
            y: 4.92,
            rgb: [20, 54, 64],
            roughness: 0.86,
            emissiveScale: 0.03,
            structuralShell: true,
          }),
          platform('chamber_machine_ring', 9.0, 1.6, 5.6, 0.26, 6.8, {
            y: 4.52,
            rgb: [90, 188, 208],
            roughness: 0.36,
            emissiveScale: 0.10,
          }),
        ],
        signage: [
          {
            offsetX: -0.8,
            y: 5.8,
            offsetZ: -6.8,
            text: 'MAIN TANK',
            width: 5.4,
            height: 1.5,
          },
        ],
      },
      {
        id: 'filtration_hazard_room',
        label: 'Filtration Hazard Room',
        x: 28,
        z: -2,
        w: 12,
        d: 12,
        floorY: 0.92,
        ceilingY: 5.8,
        floorSurfaceType: 'wet_service_deck',
        wallLanguage: 'filtration_bay',
        landmarks: ['spill gate', 'drain lane'],
        shell: {
          rgb: [20, 58, 72],
          roughness: 0.88,
          wallThickness: 1.1,
          floorSkirt: 0.54,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('hazard_safe_lane', -2.6, 0.0, 3.6, 8.8, 'wet_service_deck', {
            floorY: 0.92,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('hazard_danger_lane', 2.2, 0.2, 5.2, 8.2, 'maintenance_plate', {
            floorY: 0.92,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('hazard_north_apron', 0.0, 4.2, 9.0, 2.4, 'shell_service_deck', {
            floorY: 0.96,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
        ],
        checkpoints: [
          {
            id: 'cp_filtration_core',
            anchorId: 'cp_filtration_core',
            offsetX: -2.4,
            offsetZ: 0.0,
            label: 'Filtration Hazard Room',
          },
        ],
        decorBlocks: [
          block('hazard_safe_curb', -2.6, 0.0, 3.8, 0.44, 8.8, {
            y: 1.34,
            rgb: [88, 134, 142],
            roughness: 0.66,
            emissiveScale: 0.03,
          }),
          block('hazard_spill_gate_frame', 1.8, 0.0, 6.4, 4.8, 1.0, {
            rgb: [22, 66, 80],
            roughness: 0.84,
            emissiveScale: 0.04,
            solid: true,
            blockerReason: 'hazard-frame',
          }),
          block('hazard_machine_stack', 4.4, 0.0, 2.8, 5.4, 4.0, {
            rgb: [54, 110, 124],
            roughness: 0.74,
            emissiveScale: 0.05,
            solid: true,
            blockerReason: 'machine-bank',
          }),
          block('hazard_backwall', 0.0, 5.8, 9.8, 5.8, 1.0, {
            rgb: [16, 46, 56],
            roughness: 0.88,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'room-boundary',
          }),
          block('hazard_spill_header', 1.8, 0.0, 6.0, 0.52, 5.2, {
            y: 5.12,
            rgb: [18, 52, 64],
            roughness: 0.86,
            emissiveScale: 0.03,
          }),
          block('hazard_drain_bank', 4.8, -4.0, 4.8, 1.2, 2.0, {
            y: 0.62,
            rgb: [18, 44, 54],
            roughness: 0.92,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'drain-bank',
          }),
          block('hazard_west_portal_mass', -5.0, 0.0, 1.8, 4.8, 6.6, {
            rgb: [16, 46, 56],
            roughness: 0.90,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'portal-edge',
          }),
          block('hazard_east_portal_mass', 5.0, 1.8, 1.8, 4.8, 5.0, {
            rgb: [16, 46, 56],
            roughness: 0.90,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'portal-edge',
          }),
          block('hazard_spill_sidewall', 2.6, -5.2, 6.4, 3.0, 1.0, {
            rgb: [18, 48, 58],
            roughness: 0.90,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'spill-containment',
          }),
        ],
        decorPlatforms: [
          platform('hazard_room_canopy', 1.0, 0.2, 7.8, 0.30, 6.2, {
            y: 4.86,
            rgb: [18, 52, 64],
            roughness: 0.86,
            emissiveScale: 0.03,
            structuralShell: true,
          }),
        ],
        signage: [
          {
            offsetX: 0.0,
            y: 4.9,
            offsetZ: -4.8,
            text: 'LIVE FILTRATION',
            width: 6.2,
            height: 1.5,
          },
        ],
      },
      {
        id: 'nursery_goal_room',
        label: 'Nursery Goal Room',
        x: 46,
        z: 8,
        w: 12,
        d: 12,
        floorY: 1.00,
        ceilingY: 5.8,
        floorSurfaceType: 'viewing_deck',
        wallLanguage: 'nursery_alcove',
        landmarks: ['recovery niche', 'nursery tank'],
        shell: {
          rgb: [24, 70, 84],
          roughness: 0.82,
          wallThickness: 1.1,
          floorSkirt: 0.54,
          openSides: ['west'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('goal_entry_floor', -3.2, -1.6, 4.8, 4.0, 'shell_service_deck', {
            floorY: 1.00,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('goal_room_floor', 0.4, 1.8, 7.8, 6.4, 'viewing_deck', {
            floorY: 1.00,
            walkableClassification: 'room-floor',
            roomSurface: true,
          }),
          surface('goalDeck', 2.8, 1.4, 3.0, 3.2, 'exhibit_deck', {
            floorY: 1.04,
            walkableClassification: 'goal',
            roomSurface: true,
          }),
        ],
        decorBlocks: [
          block('goal_threshold_screen_l', -4.8, -0.4, 1.8, 4.8, 4.8, {
            rgb: [18, 52, 64],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'threshold-frame',
          }),
          block('goal_threshold_screen_r', -1.4, 1.6, 1.8, 4.8, 4.8, {
            rgb: [18, 52, 64],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'threshold-frame',
          }),
          block('goal_niche_left', 0.6, 4.0, 1.4, 5.2, 5.4, {
            rgb: [18, 50, 62],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'room-boundary',
          }),
          block('goal_niche_right', 5.0, 4.0, 1.4, 5.2, 5.4, {
            rgb: [18, 50, 62],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'room-boundary',
          }),
          block('goal_backdrop_wall', 2.8, 6.8, 6.8, 5.4, 1.0, {
            rgb: [16, 48, 58],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            blockerReason: 'room-boundary',
          }),
          block('goal_recovery_tank_wall', 2.8, 5.8, 5.8, 4.8, 0.8, {
            rgb: [88, 198, 214],
            emissiveScale: 0.10,
            roughness: 0.32,
            alpha: 0.78,
            solid: true,
            interiorVisible: true,
          }),
          block('goal_recovery_tank_volume', 2.8, 7.8, 5.4, 4.4, 3.2, {
            rgb: [26, 98, 124],
            emissiveScale: 0.04,
            roughness: 0.32,
            alpha: 0.22,
            interiorVisible: true,
          }),
          block('goal_room_left_wall', -5.2, 2.0, 1.2, 5.2, 8.2, {
            rgb: [18, 50, 62],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'room-boundary',
          }),
          block('goal_room_right_wall', 6.2, 2.0, 1.2, 5.2, 8.2, {
            rgb: [18, 50, 62],
            roughness: 0.86,
            emissiveScale: 0.03,
            solid: true,
            structuralShell: true,
            blockerReason: 'room-boundary',
          }),
          block('goal_room_niche_header', 2.8, 2.4, 6.4, 0.46, 2.0, {
            y: 4.92,
            rgb: [18, 54, 64],
            roughness: 0.84,
            emissiveScale: 0.03,
            structuralShell: true,
          }),
        ],
        decorPlatforms: [
          platform('goal_niche_canopy', 2.8, 4.4, 6.6, 0.34, 5.6, {
            y: 5.82,
            rgb: [20, 56, 66],
            roughness: 0.84,
            emissiveScale: 0.03,
          }),
          platform('goal_threshold_canopy', -2.8, 0.2, 4.0, 0.28, 5.2, {
            y: 4.74,
            rgb: [20, 58, 68],
            roughness: 0.84,
            emissiveScale: 0.03,
            structuralShell: true,
          }),
        ],
        signage: [
          {
            offsetX: -0.2,
            y: 5.0,
            offsetZ: -4.4,
            text: 'NURSERY RECOVERY',
            width: 6.6,
            height: 1.5,
          },
        ],
      },
    ],
    connectors: [
      {
        id: 'arrival_to_public',
        label: 'Arrival To Public Hall',
        sourceSector: 'arrival_vestibule',
        destinationSector: 'public_exhibit_hall',
        type: 'hall',
        x: -27,
        z: 6,
        w: 4,
        d: 4,
        floorY: 0.90,
        ceilingY: 5.0,
        floorSurfaceType: 'viewing_deck',
        wallLanguage: 'public_portal',
        shell: {
          rgb: [22, 62, 76],
          roughness: 0.86,
          wallThickness: 0.9,
          floorSkirt: 0.40,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('arrival_public_floor', 0.0, 0.0, 3.6, 3.4, 'viewing_deck', {
            floorY: 0.90,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
        ],
      },
      {
        id: 'arrival_to_service',
        label: 'Arrival To Service Elbow',
        sourceSector: 'arrival_vestibule',
        destinationSector: 'service_elbow',
        type: 'hall',
        x: -27,
        z: -3,
        w: 4,
        d: 4,
        floorY: 0.88,
        ceilingY: 5.0,
        floorSurfaceType: 'shell_service_deck',
        wallLanguage: 'service_portal',
        shell: {
          rgb: [20, 58, 72],
          roughness: 0.88,
          wallThickness: 0.9,
          floorSkirt: 0.40,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('arrival_service_floor', 0.0, 0.0, 3.6, 3.4, 'shell_service_deck', {
            floorY: 0.88,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
        ],
      },
      {
        id: 'public_to_hero',
        label: 'Public Reveal Corridor',
        sourceSector: 'public_exhibit_hall',
        destinationSector: 'hero_tank_chamber',
        type: 'hall',
        x: -6,
        z: 12,
        w: 8,
        d: 4,
        floorY: 0.98,
        ceilingY: 5.2,
        floorSurfaceType: 'viewing_deck',
        wallLanguage: 'reveal_gallery',
        shell: {
          rgb: [22, 60, 74],
          roughness: 0.86,
          wallThickness: 0.9,
          floorSkirt: 0.42,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('public_reveal_floor', 0.0, 0.0, 7.2, 3.6, 'viewing_deck', {
            floorY: 0.98,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
        ],
      },
      {
        id: 'service_to_hero',
        label: 'Service Bypass',
        sourceSector: 'service_elbow',
        destinationSector: 'hero_tank_chamber',
        type: 'hall',
        x: -6,
        z: 1,
        w: 8,
        d: 4,
        floorY: 0.92,
        ceilingY: 5.0,
        floorSurfaceType: 'catwalk_grate',
        wallLanguage: 'service_bypass',
        shell: {
          rgb: [20, 58, 70],
          roughness: 0.88,
          wallThickness: 0.9,
          floorSkirt: 0.40,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('service_bypass_floor', 0.0, 0.0, 7.2, 3.4, 'catwalk_grate', {
            floorY: 0.92,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
        ],
      },
      {
        id: 'hero_to_filtration',
        label: 'Filtration Transfer',
        sourceSector: 'hero_tank_chamber',
        destinationSector: 'filtration_hazard_room',
        type: 'hall',
        x: 20,
        z: 0,
        w: 4,
        d: 4,
        floorY: 0.98,
        ceilingY: 5.0,
        floorSurfaceType: 'shell_service_deck',
        wallLanguage: 'service_transfer',
        shell: {
          rgb: [20, 58, 70],
          roughness: 0.88,
          wallThickness: 0.9,
          floorSkirt: 0.40,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('filtration_transfer_floor', 0.0, 0.0, 3.4, 3.4, 'shell_service_deck', {
            floorY: 0.98,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
        ],
      },
      {
        id: 'filtration_to_goal',
        label: 'Nursery Compression Hall',
        sourceSector: 'filtration_hazard_room',
        destinationSector: 'nursery_goal_room',
        type: 'hall',
        x: 37,
        z: 4,
        w: 6,
        d: 4,
        floorY: 0.98,
        ceilingY: 5.0,
        floorSurfaceType: 'shell_service_deck',
        wallLanguage: 'goal_compression',
        shell: {
          rgb: [22, 60, 72],
          roughness: 0.86,
          wallThickness: 0.9,
          floorSkirt: 0.40,
          openSides: ['west', 'east'],
          solid: true,
          ceiling: false,
          beamCount: 0,
        },
        surfaces: [
          surface('goal_compression_floor', 0.0, 0.0, 5.4, 3.4, 'shell_service_deck', {
            floorY: 0.98,
            walkableClassification: 'connector',
            roomSurface: true,
          }),
        ],
      },
    ],
  },
  coins: [
    { x: -40.8, y: 0, z: 1.6 },
    { x: -37.0, y: 0, z: -2.2 },
    { x: -24.8, y: 0, z: 6.2 },
    { x: -22.0, y: 0, z: 11.6 },
    { x: -18.0, y: 0, z: 15.2 },
    { x: -12.0, y: 0, z: 10.4 },
    { x: -24.2, y: 0, z: -3.0 },
    { x: -18.4, y: 0, z: -6.0 },
    { x: -12.4, y: 0, z: -2.0 },
    { x: -1.2, y: 0, z: 11.8 },
    { x: 4.8, y: 0, z: 9.0 },
    { x: 2.8, y: 0, z: 14.8 },
    { x: 10.4, y: 0, z: 6.4 },
    { x: 12.8, y: 0, z: 2.2 },
    { x: 24.8, y: 0, z: -1.8 },
    { x: 29.0, y: 0, z: -1.6 },
    { x: 41.2, y: 0, z: 5.8 },
    { x: 47.0, y: 0, z: 9.0 },
  ],
  currents: [],
  deepWaterPockets: [
    { name: 'touch_pool_pocket', x: -13.2, y: 1.94, z: 5.4, w: 4.2, h: 3.4, d: 3.8 },
    { name: 'hero_tank_pocket', x: 6.4, y: 2.36, z: 12.4, w: 7.2, h: 4.4, d: 5.8 },
  ],
  airBubblePickups: [
    { name: 'bubble_touch_pool', x: -13.0, y: 2.06, z: 5.4, radius: 0.78, refill: 8 },
    { name: 'bubble_hero_tank', x: 6.6, y: 2.54, z: 12.4, radius: 0.82, refill: 10 },
  ],
  eelRails: [
    { name: 'eel_spill_gate', x1: 27.0, y1: 1.28, x2: 30.8, y2: 1.28, z: -1.0, phaseOffset: 0.18 },
  ],
  vents: [],
  jellyfish: [
    {
      name: 'jelly_touch_pool',
      x: -13.0,
      y: 1.96,
      z: 5.4,
      bounds: { minX: -15.2, maxX: -10.8, minY: 1.2, maxY: 3.2, minZ: 3.6, maxZ: 7.0 },
      speed: 0.76,
      turnSpeed: 2.2,
    },
    {
      name: 'jelly_hero_tank',
      x: 6.8,
      y: 2.40,
      z: 12.2,
      bounds: { minX: 3.4, maxX: 10.2, minY: 1.5, maxY: 3.8, minZ: 9.4, maxZ: 15.4 },
      speed: 0.92,
      turnSpeed: 2.5,
    },
  ],
  signage: [
    { x: -17.8, y: 5.2, z: 18.8, text: 'GUEST VIEWING', width: 7.0, height: 1.5 },
    { x: -18.0, y: 4.8, z: -10.8, text: 'STAFF ONLY', width: 5.4, height: 1.4 },
    { x: 28.0, y: 4.8, z: 4.2, text: 'FILTER OUTPUT', width: 6.0, height: 1.5 },
  ],
});

export const LEVEL5 = {
  ...BASE_LEVEL5,
  coins: normalizeCoinsOnSurfaces(BASE_LEVEL5, { defaultZ: 0 }),
};
