import { normalizeCoinsOnSurfaces } from './eraLevelLayout.js';
import { compileAuthoredEraLayout } from './eraAuthoredLayout.js';

const L = 0;

const BASE_LEVEL6 = compileAuthoredEraLayout({
  totalCollectibles: 18,
  spawn: { x: -26.5, y: 1.2, z: -0.4 },
  goal: { x: 132.5, y: 2.56, z: 2.2 },
  theme: 'factory',
  showGroundVisual: false,
  showRouteRibbons: false,

  acts: [
    { id: 'A', label: 'Loading Bay', range: [-36, 28], checkpointsTo: 1 },
    { id: 'B', label: 'Machine Hall', range: [28, 96], checkpointsTo: 2 },
    { id: 'C', label: 'Crane Control', range: [96, 140], checkpointsTo: 3 },
  ],

  authoredMap: {
    id: 'pressure-works-map01',
    startSector: 'loading_bay',
    goalSector: 'control_room',
    sectors: [
      {
        id: 'loading_bay',
        label: 'Loading Bay',
        x: -20,
        z: -0.5,
        w: 30,
        d: 22,
        floorY: 0.70,
        ceilingY: 8.9,
        floorSurfaceType: 'tread_plate',
        wallLanguage: 'ribbed_steel_bay',
        landmarks: ['gantry crane', 'crate stack'],
        shell: {
          rgb: [74, 58, 42],
          roughness: 0.92,
          openSides: ['west', 'east'],
          beamCount: 4,
          beamRgb: [102, 84, 64],
        },
        surfaces: [
          { id: 'loading_floor', offsetX: 0, offsetZ: 0, w: 22, d: 14, h: 0.72, surfaceType: 'loading_plate', walkableClassification: 'bay-floor' },
          { id: 'north_apron', offsetX: -4, offsetZ: -6.3, w: 10, d: 4.4, h: 0.60, surfaceType: 'maintenance_apron', walkableClassification: 'apron' },
          { id: 'south_spur', offsetX: 4.2, offsetZ: 6.2, w: 8.4, d: 4.0, h: 0.58, surfaceType: 'maintenance_spur', walkableClassification: 'apron' },
        ],
        drops: [
          {
            name: 'boots',
            type: 'item',
            defId: 'conveyor_boots',
            offsetX: -5.8,
            offsetZ: -0.8,
            radius: 1.0,
            autoEquip: true,
            title: 'Conveyor Boots',
            subtitle: 'Passive traction on belts and oil slicks',
          },
        ],
        decorBlocks: [
          { name: 'crate_bank_west', offsetX: -11.8, offsetZ: -5.8, w: 5.8, h: 4.8, d: 4.4, rgb: [86, 68, 48], emissiveScale: 0.02, roughness: 0.92 },
          { name: 'crate_bank_south', offsetX: -7.0, offsetZ: 7.8, w: 6.2, h: 3.8, d: 3.8, rgb: [82, 64, 44], emissiveScale: 0.02, roughness: 0.92 },
          { name: 'intake_frame_east', offsetX: 13.2, offsetZ: 0.0, w: 2.4, h: 8.4, d: 10.4, rgb: [68, 52, 40], emissiveScale: 0.02, roughness: 0.88 },
        ],
        decorColumns: [
          { name: 'gantry_post_nw', offsetX: -10.6, offsetZ: -7.8, diameter: 1.2, height: 8.6, rgb: [90, 72, 54], roughness: 0.86 },
          { name: 'gantry_post_sw', offsetX: -10.4, offsetZ: 7.8, diameter: 1.2, height: 8.6, rgb: [90, 72, 54], roughness: 0.86 },
          { name: 'gantry_post_ne', offsetX: 10.8, offsetZ: -7.8, diameter: 1.2, height: 8.6, rgb: [90, 72, 54], roughness: 0.86 },
          { name: 'gantry_post_se', offsetX: 10.8, offsetZ: 7.8, diameter: 1.2, height: 8.6, rgb: [90, 72, 54], roughness: 0.86 },
        ],
        signage: [
          { offsetX: -1.0, y: 5.4, offsetZ: 8.8, text: 'LOADING BAY', width: 7.4, height: 1.8 },
        ],
      },
      {
        id: 'pressure_corridor',
        label: 'Pressure Corridor',
        x: 8,
        z: -4.5,
        w: 24,
        d: 8.2,
        floorY: 0.84,
        ceilingY: 5.8,
        floorSurfaceType: 'grated_hall',
        wallLanguage: 'pressure_corridor',
        landmarks: ['pipe chase', 'steam vent'],
        shell: {
          rgb: [70, 56, 40],
          roughness: 0.90,
          openSides: ['west', 'east'],
          beamCount: 2,
        },
        surfaces: [
          { id: 'corridor_floor', offsetX: 0, offsetZ: 0, w: 18.4, d: 5.2, h: 0.66, surfaceType: 'grate_corridor', walkableClassification: 'corridor' },
        ],
        decorBlocks: [
          { name: 'pipe_bank_north', offsetX: 0.0, offsetZ: -4.9, w: 16.6, h: 2.6, d: 1.6, y: 2.6, rgb: [92, 76, 58], emissiveScale: 0.03, roughness: 0.84 },
          { name: 'pipe_bank_south', offsetX: 0.0, offsetZ: 4.9, w: 16.6, h: 2.2, d: 1.4, y: 2.3, rgb: [92, 76, 58], emissiveScale: 0.03, roughness: 0.84 },
        ],
      },
      {
        id: 'machine_hall',
        label: 'Machine Hall',
        x: 40,
        z: -0.5,
        w: 32,
        d: 24,
        floorY: 1.18,
        ceilingY: 10.4,
        floorSurfaceType: 'machine_plate',
        wallLanguage: 'machine_bay',
        landmarks: ['press bank', 'furnace mouth'],
        shell: {
          rgb: [78, 60, 44],
          roughness: 0.88,
          openSides: ['west', 'north', 'south', 'east'],
          beamCount: 5,
          beamRgb: [108, 84, 58],
        },
        surfaces: [
          { id: 'south_floor', offsetX: -1.0, offsetZ: -5.2, w: 22.0, d: 8.4, h: 0.72, surfaceType: 'machine_floor', walkableClassification: 'bay-floor' },
          { id: 'north_floor', offsetX: 2.6, offsetZ: 5.8, w: 16.2, d: 6.8, h: 0.70, surfaceType: 'machine_floor', walkableClassification: 'bay-floor' },
          { id: 'center_pad', offsetX: 4.6, offsetZ: 0.0, w: 10.2, d: 4.8, h: 0.68, surfaceType: 'service_pad', walkableClassification: 'bay-pad' },
        ],
        checkpoints: [
          { id: 'cp_press_hall', offsetX: -8.4, offsetZ: -3.0, label: 'Machine Hall' },
        ],
        drops: [
          {
            name: 'foam',
            type: 'item',
            defId: 'foam_blaster',
            offsetX: -1.6,
            offsetZ: 5.2,
            radius: 1.0,
            autoEquip: true,
            title: 'Foam Blaster',
            subtitle: 'Ctrl / Enter / Click to push toys away',
          },
        ],
        decorBlocks: [
          { name: 'press_bank_south', offsetX: -2.5, offsetZ: -10.0, w: 18.4, h: 7.2, d: 3.2, rgb: [92, 70, 44], emissiveScale: 0.03, roughness: 0.86 },
          { name: 'press_bank_north', offsetX: 1.6, offsetZ: 10.2, w: 16.4, h: 7.0, d: 3.0, rgb: [96, 72, 46], emissiveScale: 0.03, roughness: 0.86 },
          { name: 'furnace_mass', offsetX: 12.2, offsetZ: 6.2, w: 7.6, h: 8.6, d: 7.2, rgb: [124, 78, 30], emissiveScale: 0.08, roughness: 0.80 },
          { name: 'servo_bank', offsetX: 12.0, offsetZ: -6.8, w: 7.8, h: 6.8, d: 5.4, rgb: [86, 68, 46], emissiveScale: 0.03, roughness: 0.86 },
        ],
        decorColumns: [
          { name: 'hall_post_w1', offsetX: -12.2, offsetZ: -8.8, diameter: 1.1, height: 9.8, rgb: [96, 78, 54], roughness: 0.84 },
          { name: 'hall_post_w2', offsetX: -12.2, offsetZ: 8.8, diameter: 1.1, height: 9.8, rgb: [96, 78, 54], roughness: 0.84 },
          { name: 'hall_post_e1', offsetX: 12.6, offsetZ: -8.8, diameter: 1.1, height: 9.8, rgb: [96, 78, 54], roughness: 0.84 },
          { name: 'hall_post_e2', offsetX: 12.6, offsetZ: 8.8, diameter: 1.1, height: 9.8, rgb: [96, 78, 54], roughness: 0.84 },
        ],
        signage: [
          { offsetX: 0.0, y: 6.2, offsetZ: 11.4, text: 'PRESS HALL', width: 6.6, height: 1.8 },
        ],
      },
      {
        id: 'service_loop',
        label: 'Service Loop',
        x: 64,
        z: -12.2,
        w: 30,
        d: 10.5,
        floorY: 1.54,
        ceilingY: 6.8,
        floorSurfaceType: 'service_grate',
        wallLanguage: 'maintenance_passage',
        landmarks: ['gear pit', 'service duct'],
        shell: {
          rgb: [68, 54, 40],
          roughness: 0.90,
          openSides: ['west', 'east'],
          beamCount: 3,
        },
        surfaces: [
          { id: 'loop_floor', offsetX: 0, offsetZ: 0, w: 24.6, d: 5.2, h: 0.64, surfaceType: 'grate_catwalk', walkableClassification: 'corridor' },
          { id: 'loop_overlook', offsetX: 8.2, offsetZ: 2.3, w: 7.8, d: 3.2, h: 0.56, surfaceType: 'service_pad', walkableClassification: 'bay-pad' },
        ],
        drops: [
          {
            name: 'hat',
            type: 'item',
            defId: 'hard_hat',
            offsetX: 4.8,
            offsetZ: -0.3,
            radius: 0.95,
            autoEquip: true,
            title: 'Hard Hat',
            subtitle: '+20% electric resist',
          },
        ],
        decorBlocks: [
          { name: 'gear_pit', offsetX: -2.0, offsetZ: -4.6, w: 8.2, h: 2.8, d: 1.8, y: 2.0, rgb: [88, 72, 50], emissiveScale: 0.03, roughness: 0.84 },
          { name: 'duct_bank', offsetX: 8.8, offsetZ: 4.7, w: 9.4, h: 2.4, d: 1.6, y: 2.4, rgb: [90, 74, 56], emissiveScale: 0.02, roughness: 0.86 },
        ],
      },
      {
        id: 'furnace_bridge',
        label: 'Furnace Bridge',
        x: 68,
        z: 9.2,
        w: 28,
        d: 10,
        floorY: 1.98,
        ceilingY: 8.8,
        floorSurfaceType: 'heat_bridge',
        wallLanguage: 'furnace_bridge',
        landmarks: ['furnace stack', 'valve shelf'],
        shell: {
          rgb: [88, 62, 36],
          roughness: 0.84,
          openSides: ['west', 'east'],
          beamCount: 3,
          beamRgb: [120, 88, 54],
        },
        surfaces: [
          { id: 'bridge_floor', offsetX: 0, offsetZ: 0, w: 22.4, d: 4.8, h: 0.64, surfaceType: 'heat_bridge', walkableClassification: 'bridge' },
          { id: 'valve_shelf', offsetX: -1.6, offsetZ: -2.8, w: 10.2, d: 2.8, h: 0.56, surfaceType: 'service_shelf', walkableClassification: 'ledge' },
        ],
        decorBlocks: [
          { name: 'furnace_stack', offsetX: 10.4, offsetZ: 4.8, w: 6.8, h: 10.4, d: 4.4, rgb: [120, 80, 32], emissiveScale: 0.08, roughness: 0.78 },
          { name: 'burner_bank', offsetX: -10.8, offsetZ: 4.7, w: 8.4, h: 5.2, d: 2.2, rgb: [104, 72, 40], emissiveScale: 0.04, roughness: 0.82 },
        ],
      },
      {
        id: 'crane_bay',
        label: 'Crane Bay',
        x: 100,
        z: 0.5,
        w: 36,
        d: 26,
        floorY: 2.30,
        ceilingY: 11.8,
        floorSurfaceType: 'crane_deck',
        wallLanguage: 'crane_bay',
        landmarks: ['crane tower', 'assembly drum'],
        shell: {
          rgb: [74, 58, 44],
          roughness: 0.86,
          openSides: ['west', 'east'],
          beamCount: 5,
          beamRgb: [108, 86, 60],
        },
        surfaces: [
          { id: 'crane_floor', offsetX: -1.0, offsetZ: -2.6, w: 24.6, d: 11.6, h: 0.74, surfaceType: 'crane_plate', walkableClassification: 'bay-floor' },
          { id: 'north_apron', offsetX: 1.0, offsetZ: 8.2, w: 16.8, d: 5.2, h: 0.60, surfaceType: 'assembly_apron', walkableClassification: 'apron' },
          { id: 'south_catwalk', offsetX: -1.0, offsetZ: -9.4, w: 18.2, d: 4.0, h: 0.58, surfaceType: 'catwalk', walkableClassification: 'catwalk' },
        ],
        checkpoints: [
          { id: 'cp_crane_bay', offsetX: -8.4, offsetZ: -2.2, label: 'Crane Bay' },
        ],
        drops: [
          {
            name: 'belt',
            type: 'item',
            defId: 'tool_belt',
            offsetX: 5.6,
            offsetZ: 7.0,
            radius: 0.95,
            autoEquip: true,
            title: 'Tool Belt',
            subtitle: 'Extra carrying room and a little speed',
          },
        ],
        decorBlocks: [
          { name: 'crane_tower', offsetX: 11.2, offsetZ: -8.0, w: 6.8, h: 11.4, d: 5.2, rgb: [88, 70, 50], emissiveScale: 0.03, roughness: 0.84 },
          { name: 'assembly_drum', offsetX: 10.4, offsetZ: 8.2, w: 8.2, h: 7.6, d: 6.2, rgb: [100, 78, 52], emissiveScale: 0.03, roughness: 0.84 },
          { name: 'control_bank', offsetX: -12.4, offsetZ: 8.8, w: 8.8, h: 5.2, d: 3.4, rgb: [92, 72, 50], emissiveScale: 0.03, roughness: 0.86 },
        ],
        decorColumns: [
          { name: 'crane_post_nw', offsetX: -13.0, offsetZ: -10.2, diameter: 1.3, height: 11.2, rgb: [94, 76, 54], roughness: 0.84 },
          { name: 'crane_post_sw', offsetX: -13.0, offsetZ: 10.2, diameter: 1.3, height: 11.2, rgb: [94, 76, 54], roughness: 0.84 },
          { name: 'crane_post_ne', offsetX: 13.0, offsetZ: -10.2, diameter: 1.3, height: 11.2, rgb: [94, 76, 54], roughness: 0.84 },
          { name: 'crane_post_se', offsetX: 13.0, offsetZ: 10.2, diameter: 1.3, height: 11.2, rgb: [94, 76, 54], roughness: 0.84 },
        ],
      },
      {
        id: 'control_room',
        label: 'Control Room',
        x: 128,
        z: 2.2,
        w: 20,
        d: 16,
        floorY: 2.54,
        ceilingY: 8.6,
        floorSurfaceType: 'control_floor',
        wallLanguage: 'control_room',
        landmarks: ['signal wall', 'goal control rail'],
        shell: {
          rgb: [72, 56, 42],
          roughness: 0.88,
          openSides: ['west'],
          beamCount: 2,
          beamRgb: [102, 82, 56],
        },
        surfaces: [
          { id: 'goal_deck', name: 'goalDeck', offsetX: 0.0, offsetZ: 0.0, w: 14.4, d: 8.4, h: 0.76, surfaceType: 'control_floor', walkableClassification: 'goal-floor' },
          { id: 'console_shelf', offsetX: -2.8, offsetZ: -4.8, w: 6.2, d: 3.0, h: 0.54, surfaceType: 'console_shelf', walkableClassification: 'ledge' },
        ],
        checkpoints: [
          { id: 'cp_control_room', offsetX: -8.0, offsetZ: 0.0, label: 'Control Room' },
        ],
        decorBlocks: [
          { name: 'signal_wall', offsetX: 8.8, offsetZ: 0.0, w: 2.2, h: 6.2, d: 9.6, rgb: [88, 72, 52], emissiveScale: 0.03, roughness: 0.84 },
          { name: 'console_bank', offsetX: 1.8, offsetZ: -5.8, w: 8.0, h: 3.2, d: 2.0, y: 3.0, rgb: [90, 74, 52], emissiveScale: 0.03, roughness: 0.84 },
        ],
        signage: [
          { offsetX: 0.0, y: 6.0, offsetZ: 7.0, text: 'ASSEMBLY CONTROL', width: 8.0, height: 1.9 },
        ],
      },
    ],
    connectors: [
      {
        id: 'load_to_corridor',
        sourceSector: 'loading_bay',
        destinationSector: 'pressure_corridor',
        type: 'doorway',
        x: -4,
        z: -3.1,
        w: 10,
        d: 6,
        floorY: 0.78,
        ceilingY: 6.4,
        floorSurfaceType: 'threshold',
        wallLanguage: 'door_frame',
        landmarks: ['intake threshold'],
        shell: false,
        surfaces: [
          { id: 'threshold_a', offsetX: -2.2, offsetZ: 0.0, w: 3.4, d: 4.8, h: 0.58, floorY: 0.76, surfaceType: 'threshold', walkableClassification: 'connector' },
          { id: 'threshold_b', offsetX: 1.8, offsetZ: 0.0, w: 3.4, d: 4.8, h: 0.60, floorY: 0.84, surfaceType: 'threshold', walkableClassification: 'connector' },
        ],
        decorBlocks: [
          { name: 'frame_left', offsetX: -4.8, offsetZ: 0.0, w: 1.0, h: 6.0, d: 5.8, rgb: [86, 68, 48], emissiveScale: 0.02, roughness: 0.88 },
          { name: 'frame_right', offsetX: 4.8, offsetZ: 0.0, w: 1.0, h: 6.0, d: 5.8, rgb: [86, 68, 48], emissiveScale: 0.02, roughness: 0.88 },
        ],
      },
      {
        id: 'corridor_to_hall',
        sourceSector: 'pressure_corridor',
        destinationSector: 'machine_hall',
        type: 'hall',
        x: 20,
        z: -4.4,
        w: 12,
        d: 6,
        floorY: 1.02,
        ceilingY: 6.8,
        floorSurfaceType: 'hall_rise',
        wallLanguage: 'pipe_hall',
        landmarks: ['hall rise'],
        shell: {
          rgb: [72, 58, 42],
          roughness: 0.88,
          openSides: ['west', 'east'],
          beamCount: 2,
        },
        surfaces: [
          { id: 'hall_rise_a', offsetX: -3.2, offsetZ: 0.0, w: 3.6, d: 4.8, h: 0.58, floorY: 0.92, surfaceType: 'connector_step', walkableClassification: 'stairs' },
          { id: 'hall_rise_b', offsetX: 0.2, offsetZ: 0.0, w: 3.6, d: 4.8, h: 0.60, floorY: 1.04, surfaceType: 'connector_step', walkableClassification: 'stairs' },
          { id: 'hall_rise_c', offsetX: 3.6, offsetZ: 0.0, w: 3.2, d: 4.8, h: 0.62, floorY: 1.18, surfaceType: 'connector_step', walkableClassification: 'stairs' },
        ],
      },
      {
        id: 'hall_to_service',
        sourceSector: 'machine_hall',
        destinationSector: 'service_loop',
        type: 'stairs',
        x: 54,
        z: -8.8,
        w: 16,
        d: 6,
        floorY: 1.38,
        ceilingY: 6.8,
        floorSurfaceType: 'service_rise',
        wallLanguage: 'service_stair',
        landmarks: ['service stair'],
        shell: false,
        surfaces: [
          { id: 'service_step_a', offsetX: -5.2, offsetZ: 0.0, w: 3.6, d: 4.6, h: 0.54, floorY: 1.28, surfaceType: 'step', walkableClassification: 'stairs' },
          { id: 'service_step_b', offsetX: -1.6, offsetZ: 0.0, w: 3.6, d: 4.6, h: 0.54, floorY: 1.40, surfaceType: 'step', walkableClassification: 'stairs' },
          { id: 'service_step_c', offsetX: 1.8, offsetZ: 0.0, w: 3.6, d: 4.6, h: 0.54, floorY: 1.54, surfaceType: 'step', walkableClassification: 'stairs' },
          { id: 'service_step_d', offsetX: 5.2, offsetZ: 0.0, w: 3.2, d: 4.6, h: 0.54, floorY: 1.54, surfaceType: 'landing', walkableClassification: 'connector' },
        ],
      },
      {
        id: 'hall_to_furnace',
        sourceSector: 'machine_hall',
        destinationSector: 'furnace_bridge',
        type: 'ramp',
        x: 54,
        z: 7.2,
        w: 18,
        d: 6,
        floorY: 1.56,
        ceilingY: 7.6,
        floorSurfaceType: 'furnace_rise',
        wallLanguage: 'furnace_entry',
        landmarks: ['furnace rise'],
        shell: false,
        surfaces: [
          { id: 'furnace_step_a', offsetX: -6.0, offsetZ: 0.0, w: 3.8, d: 4.4, h: 0.54, floorY: 1.34, surfaceType: 'step', walkableClassification: 'stairs' },
          { id: 'furnace_step_b', offsetX: -2.2, offsetZ: 0.0, w: 3.8, d: 4.4, h: 0.54, floorY: 1.56, surfaceType: 'step', walkableClassification: 'stairs' },
          { id: 'furnace_step_c', offsetX: 1.6, offsetZ: 0.0, w: 3.8, d: 4.4, h: 0.54, floorY: 1.78, surfaceType: 'step', walkableClassification: 'stairs' },
          { id: 'furnace_step_d', offsetX: 5.4, offsetZ: 0.0, w: 3.4, d: 4.4, h: 0.54, floorY: 1.98, surfaceType: 'landing', walkableClassification: 'connector' },
        ],
      },
      {
        id: 'service_to_crane',
        sourceSector: 'service_loop',
        destinationSector: 'crane_bay',
        type: 'bridge',
        x: 82,
        z: -8.8,
        w: 20,
        d: 5.4,
        floorY: 1.90,
        ceilingY: 7.0,
        floorSurfaceType: 'service_bridge',
        wallLanguage: 'catwalk_bridge',
        landmarks: ['gear lift approach'],
        shell: {
          rgb: [70, 56, 44],
          roughness: 0.88,
          openSides: ['west', 'east'],
          ceiling: false,
        },
        surfaces: [
          { id: 'service_bridge_a', offsetX: -6.0, offsetZ: 0.0, w: 3.8, d: 4.2, h: 0.54, floorY: 1.68, surfaceType: 'catwalk', walkableClassification: 'bridge' },
          { id: 'service_bridge_b', offsetX: -2.0, offsetZ: 0.0, w: 3.8, d: 4.2, h: 0.54, floorY: 1.88, surfaceType: 'catwalk', walkableClassification: 'bridge' },
          { id: 'service_bridge_c', offsetX: 2.0, offsetZ: 0.0, w: 3.8, d: 4.2, h: 0.54, floorY: 2.08, surfaceType: 'catwalk', walkableClassification: 'bridge' },
          { id: 'service_bridge_d', offsetX: 6.0, offsetZ: 0.0, w: 3.8, d: 4.2, h: 0.54, floorY: 2.30, surfaceType: 'catwalk', walkableClassification: 'bridge' },
        ],
        decorColumns: [
          { name: 'catwalk_post_a', offsetX: -7.8, offsetZ: -1.8, diameter: 0.8, height: 4.8, rgb: [92, 76, 58], roughness: 0.84 },
          { name: 'catwalk_post_b', offsetX: 7.8, offsetZ: 1.8, diameter: 0.8, height: 4.8, rgb: [92, 76, 58], roughness: 0.84 },
        ],
      },
      {
        id: 'furnace_to_crane',
        sourceSector: 'furnace_bridge',
        destinationSector: 'crane_bay',
        type: 'bridge',
        x: 84,
        z: 7.6,
        w: 20,
        d: 5.4,
        floorY: 2.16,
        ceilingY: 7.2,
        floorSurfaceType: 'furnace_bridge',
        wallLanguage: 'heat_bridge',
        landmarks: ['bridge over furnace channel'],
        shell: {
          rgb: [84, 62, 38],
          roughness: 0.84,
          openSides: ['west', 'east'],
          ceiling: false,
        },
        surfaces: [
          { id: 'furnace_bridge_a', offsetX: -6.0, offsetZ: 0.0, w: 3.8, d: 4.2, h: 0.54, floorY: 2.04, surfaceType: 'heat_bridge', walkableClassification: 'bridge' },
          { id: 'furnace_bridge_b', offsetX: -2.0, offsetZ: 0.0, w: 3.8, d: 4.2, h: 0.54, floorY: 2.16, surfaceType: 'heat_bridge', walkableClassification: 'bridge' },
          { id: 'furnace_bridge_c', offsetX: 2.0, offsetZ: 0.0, w: 3.8, d: 4.2, h: 0.54, floorY: 2.24, surfaceType: 'heat_bridge', walkableClassification: 'bridge' },
          { id: 'furnace_bridge_d', offsetX: 6.0, offsetZ: 0.0, w: 3.8, d: 4.2, h: 0.54, floorY: 2.30, surfaceType: 'heat_bridge', walkableClassification: 'bridge' },
        ],
      },
      {
        id: 'crane_to_control',
        sourceSector: 'crane_bay',
        destinationSector: 'control_room',
        type: 'doorway',
        x: 114,
        z: 1.8,
        w: 12,
        d: 5.2,
        floorY: 2.42,
        ceilingY: 7.2,
        floorSurfaceType: 'control_threshold',
        wallLanguage: 'control_entry',
        landmarks: ['control threshold'],
        shell: false,
        surfaces: [
          { id: 'control_threshold_a', offsetX: -3.2, offsetZ: 0.0, w: 3.4, d: 4.2, h: 0.52, floorY: 2.38, surfaceType: 'threshold', walkableClassification: 'connector' },
          { id: 'control_threshold_b', offsetX: 0.0, offsetZ: 0.0, w: 3.4, d: 4.2, h: 0.52, floorY: 2.46, surfaceType: 'threshold', walkableClassification: 'connector' },
          { id: 'control_threshold_c', offsetX: 3.2, offsetZ: 0.0, w: 3.2, d: 4.2, h: 0.52, floorY: 2.54, surfaceType: 'threshold', walkableClassification: 'connector' },
        ],
        decorBlocks: [
          { name: 'control_frame_left', offsetX: -5.0, offsetZ: 0.0, w: 0.9, h: 5.6, d: 5.4, rgb: [86, 68, 48], emissiveScale: 0.02, roughness: 0.88 },
          { name: 'control_frame_right', offsetX: 5.0, offsetZ: 0.0, w: 0.9, h: 5.6, d: 5.4, rgb: [86, 68, 48], emissiveScale: 0.02, roughness: 0.88 },
        ],
      },
    ],
  },

  coins: [
    { x: -27.4, y: 0, z: -1.0 }, { x: -20.5, y: 0, z: -5.0 },
    { x: -12.0, y: 0, z:  4.6 }, { x:  -3.2, y: 0, z: -3.0 },
    { x:   7.0, y: 0, z: -4.8 }, { x:  18.8, y: 0, z: -4.4 },
    { x:  30.5, y: 0, z: -5.2 }, { x:  38.8, y: 0, z:  5.8 },
    { x:  46.0, y: 0, z: -0.2 }, { x:  54.0, y: 0, z: -8.6 },
    { x:  63.0, y: 0, z: -12.2 }, { x:  67.5, y: 0, z:  9.0 },
    { x:  79.0, y: 0, z: -8.6 }, { x:  82.4, y: 0, z:  7.4 },
    { x:  95.0, y: 0, z: -2.6 }, { x: 104.0, y: 0, z:  8.0 },
    { x: 114.0, y: 0, z:  1.6 }, { x: 129.0, y: 0, z:  2.0 },
  ],

  conveyors: [
    { name: 'beltA1', x: -10.0, y: 1.08, z: -0.6, w: 10.0, h: 2.2, d: 5.2, pushX: 3.4, pushZ: -0.2 },
    { name: 'beltA2', x:   8.0, y: 1.28, z: -4.4, w: 10.0, h: 2.2, d: 4.6, pushX: 3.2, pushZ:  0.0 },
    { name: 'beltC1', x:  97.0, y: 2.62, z: -2.8, w: 12.0, h: 2.6, d: 5.8, pushX: 4.0, pushZ: -0.3 },
  ],

  oilSlicks: [
    { name: 'oil_machine', x: 34.0, y: 1.04, z: -5.8, w: 5.6, h: 0.3, d: 3.2, slipX: 1.3, slipZ: -0.2 },
    { name: 'oil_catwalk', x: 98.0, y: 2.12, z: -9.4, w: 5.0, h: 0.3, d: 2.8, slipX: -1.0, slipZ: 0.2 },
  ],

  presses: [
    { name: 'press_machine_a', x: 34.0, y: 3.40, z: -2.6, w: 4.2, h: 5.4, d: 4.6, warn: 0.8, active: 0.6, cooldown: 1.0, phaseOffset: 0.00 },
    { name: 'press_machine_b', x: 46.0, y: 3.58, z:  4.8, w: 4.2, h: 5.4, d: 4.6, warn: 0.8, active: 0.6, cooldown: 1.1, phaseOffset: 0.32 },
    { name: 'press_crane',     x: 102.0, y: 4.12, z: -2.4, w: 4.2, h: 5.6, d: 4.6, warn: 0.8, active: 0.6, cooldown: 1.0, phaseOffset: 0.64 },
  ],

  gearLifts: [
    { name: 'gearLift_service', x: 79.0, y: 1.42, z: -12.0, w: 5.8, h: 0.76, d: 5.8, travel: 1.0, speed: 0.82 },
    { name: 'gearLift_crane',   x: 106.0, y: 2.04, z:  8.6, w: 6.2, h: 0.78, d: 6.2, travel: 1.2, speed: 0.88 },
  ],

  enemies: [
    {
      name: 'toyA1',
      kind: 'toy',
      x: -15.0,
      y: 1.12,
      z: 0.5,
      radius: 0.8,
      bounds: { minX: -24.0, maxX: -8.0, minY: 0.6, maxY: 1.5, minZ: -5.0, maxZ: 4.5 },
      speed: 1.45,
      turnSpeed: 2.6,
    },
    {
      name: 'toyB1',
      kind: 'toy',
      x: 37.0,
      y: 1.60,
      z: -4.0,
      radius: 0.82,
      bounds: { minX: 28.0, maxX: 46.0, minY: 0.9, maxY: 1.8, minZ: -7.5, maxZ: 0.5 },
      speed: 1.6,
      turnSpeed: 2.8,
    },
    {
      name: 'toyC1',
      kind: 'toy',
      x: 99.0,
      y: 2.72,
      z: -2.4,
      radius: 0.84,
      bounds: { minX: 90.0, maxX: 108.0, minY: 2.0, maxY: 2.9, minZ: -5.5, maxZ: 2.0 },
      speed: 1.72,
      turnSpeed: 2.9,
    },
  ],

  signage: [
    { x: 68.0, y: 5.4, z: -17.8, text: 'SERVICE LOOP', width: 6.4, height: 1.7 },
    { x: 74.0, y: 5.9, z: 14.8, text: 'FURNACE BRIDGE', width: 7.8, height: 1.8 },
    { x: 101.0, y: 6.4, z: 12.4, text: 'CRANE PLATFORM', width: 7.8, height: 1.8 },
  ],
});

export const LEVEL6 = {
  ...BASE_LEVEL6,
  coins: normalizeCoinsOnSurfaces(BASE_LEVEL6, { defaultZ: L }),
};
